{{- if .Values.bitwardenSecret.enabled -}}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ include "argentum.fullname" . }}-bw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argentum.labels" . | nindent 4 }}
spec:
  organizationId: {{ .Values.bitwardenSecret.organizationId | quote }}
  secretName: {{ include "argentum.secretName" . }}
  authToken:
    secretName: {{ .Values.bitwardenSecret.authTokenSecretName }}
    secretKey: {{ .Values.bitwardenSecret.authTokenSecretKey }}
  map:
    {{- range .Values.bitwardenSecret.secrets }}
    - bwSecretId: {{ .bwSecretId | quote }}
      secretKeyName: {{ .secretKeyName }}
    {{- end }}
{{- end }}
