package domain

import (
	"context"
	"strings"
)

// ReportBranding is the tenant's identity on the documents Argentum generates:
// the PDF a customer forwards to their board, and the deck presented from it.
//
// Every field is optional and every field falls back independently. A tenant
// with a logo and no colour gets their logo and Argentum's red — the renderer
// resolves per field rather than per object, because "you configured one thing,
// so we stopped using our defaults for the rest" is how a half-configured
// document ends up looking broken rather than partly branded.
//
// It is stored as one jsonb column on companies (migration 022). The zero value
// is a valid, fully-defaulted branding, which is what lets a company that has
// never opened the Reports tab render exactly as it did before this existed.
type ReportBranding struct {
	// LogoKey is the object-storage key of the tenant's mark, written by the
	// upload endpoint as branding/{company_id}/logo.png. It is a key and not a
	// URL because a URL from object storage expires; the renderer re-reads the
	// object every time it draws a document.
	LogoKey string `json:"logo_key,omitempty"`

	// PrimaryColor is a #RRGGBB accent replacing the brand red on rules,
	// headings and KPI emphasis. It is validated for contrast against white
	// before it is stored — see app.ValidateBrandingColor. Chart series are
	// deliberately *not* recoloured from it; see the note in the branding
	// service.
	PrimaryColor string `json:"primary_color,omitempty"`

	// FooterText is a legal line carried on every page and every slide, for the
	// tenants whose compliance team requires one.
	FooterText string `json:"footer_text,omitempty"`

	// LegalName is the entity the document belongs to when it is not the
	// company's display name — "PT Contoh Sejahtera Tbk" on a document from a
	// workspace called "Contoh". It becomes the PDF's Author property, which is
	// what a document-management system files it under.
	LegalName string `json:"legal_name,omitempty"`

	// Locale is the default document language ("id", "en") when the model does
	// not name one. Without it the locale is derived from the currency, which
	// is right often enough to be a good default and wrong often enough to be
	// worth overriding.
	Locale string `json:"locale,omitempty"`

	// ConfidentialityLabel is the default label ("Internal", "Confidential")
	// for documents whose spec does not carry one. Empty means no label, which
	// is a legitimate choice and not an unset one.
	ConfidentialityLabel string `json:"confidentiality_label,omitempty"`

	// ShowArgentumCredit keeps the "Generated by Argentum" footer line. It
	// defaults to true through the pointer: a tenant who has never configured
	// branding at all gets the credit, and only an explicit false removes it.
	// A plain bool would make "not configured" and "opted out" the same value.
	ShowArgentumCredit *bool `json:"show_argentum_credit,omitempty"`
}

// Normalize trims the free-text fields and upper-cases the colour so that
// `#f25c5c` and `#F25C5C` are one value rather than two. It does not validate:
// validation needs the contrast maths, which lives with the renderer's colour
// type, and domain does not import the renderer.
func (b *ReportBranding) Normalize() {
	if b == nil {
		return
	}
	b.LogoKey = strings.TrimSpace(b.LogoKey)
	b.PrimaryColor = strings.ToUpper(strings.TrimSpace(b.PrimaryColor))
	b.FooterText = strings.TrimSpace(b.FooterText)
	b.LegalName = strings.TrimSpace(b.LegalName)
	b.Locale = strings.ToLower(strings.TrimSpace(b.Locale))
	b.ConfidentialityLabel = strings.TrimSpace(b.ConfidentialityLabel)
}

// CreditVisible resolves the three-state pointer to the answer the renderer
// needs. Nil — never configured — shows the credit.
func (b *ReportBranding) CreditVisible() bool {
	if b == nil || b.ShowArgentumCredit == nil {
		return true
	}
	return *b.ShowArgentumCredit
}

// BrandingRepository is the persistence contract for the branding record.
// It is separate from CompanyRepository.Update on purpose: Update writes name,
// slug and currency, and a branding save that went through it would have to
// read-modify-write the whole company row, racing every other settings change.
type BrandingRepository interface {
	GetBranding(ctx context.Context, companyID string) (*ReportBranding, error)
	SaveBranding(ctx context.Context, companyID string, b *ReportBranding) error
}
