package domain

import (
	"context"
	"strings"
	"time"
)

// DBConnection is a tenant-supplied analytical database connection. The DSN
// is stored encrypted at rest; only the database type is in plaintext so the
// agent can dispatch to the right driver.
type DBConnection struct {
	ID           string `json:"id"`
	CompanyID    string `json:"company_id"`
	DBType       string `json:"db_type"` // matches one of internal/adapters/db.Supported
	DSNEncrypted []byte `json:"-"`
	IsDefault    bool   `json:"is_default"`
	Label        string `json:"label,omitempty"`
	// Description is a short hint about what this database contains, used by
	// the LLM agent when picking which source to query.
	Description string `json:"description"`
	// DescriptionSource records how Description was populated:
	//   ""       — uninitialised, autogen pending
	//   "auto"   — generated by the ConnectionDescriber LLM
	//   "manual" — set by the user; autogen must not overwrite it
	DescriptionSource string `json:"description_source"`
	// Origin says who built this source: OriginTenant for a warehouse somebody
	// connected, OriginDocument for one this product materialized out of
	// uploaded PDFs (T-P6).
	//
	// It reaches the agent through `list_sources`, and that is the reason it
	// exists rather than being inferrable from a label. An agent choosing
	// between two sources should know that one of them is *derived* — its
	// figures are this product's reading of a page, not a system of record —
	// because the right follow-up when the two disagree depends on which is
	// which.
	Origin string `json:"origin"`
	// EnableTableEmbedding turns on the embedding-based table picker for
	// this source. When true and embeddings exist, the chat runner injects
	// a top-K relevant-table hint into the user's message so the agent can
	// call get_schema pre-filtered instead of dumping the full catalog.
	EnableTableEmbedding bool `json:"enable_table_embedding"`
	// EmbeddingsIndexedAt records when the table_embeddings rows for this
	// source were last (re)built. Nil means never indexed.
	EmbeddingsIndexedAt *time.Time `json:"embeddings_indexed_at,omitempty"`
	// Allowlist restricts which tables and columns of this source the agent may
	// read (T-H12). The zero value is unrestricted, which is what every row
	// written before migration 068 has to keep meaning.
	Allowlist Allowlist `json:"allowlist"`
	// Freshness says how to find out when this source last loaded, and how old
	// is too old (T-F1). The zero value is unchecked.
	Freshness SourceFreshness `json:"freshness"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// SourceFreshness is a source's freshness setup as it is stored: an expression
// and two thresholds in minutes.
//
// It is a storage and transport shape only — the policy lives in
// internal/freshness, which this package deliberately does not import. Minutes
// rather than a Duration because the two things that read this are a Postgres
// INTEGER column and a settings form, and both want a number.
type SourceFreshness struct {
	// SQL is a single SELECT returning one row and one column: the moment this
	// source last loaded. Empty means unchecked, and an unchecked source reports
	// `unknown`, which says nothing to anybody.
	SQL string `json:"sql,omitempty"`
	// WarnAfterMins is how old the data may be before an answer dates itself.
	// Zero means never warn.
	WarnAfterMins int `json:"warn_after_mins,omitempty"`
	// StaleAfterMins is how old the data may be before an answer carries a
	// notice the server wrote. Zero with a non-empty SQL is refused on save:
	// an expression that can never report stale is a setting that silently does
	// nothing.
	StaleAfterMins int `json:"stale_after_mins,omitempty"`
}

// Configured reports whether this source has anything to probe.
func (f SourceFreshness) Configured() bool { return strings.TrimSpace(f.SQL) != "" }

// Description sources.
const (
	DescriptionSourceAuto   = "auto"
	DescriptionSourceManual = "manual"
)

// Connection origins.
const (
	// OriginTenant is a database somebody connected. The default, and what
	// every row that existed before migration 060 is.
	OriginTenant = "tenant"
	// OriginDocument is the document warehouse: rows this product extracted
	// from uploaded PDFs and a reviewer applied.
	OriginDocument = "document"
)

// ConnectionRepository is the persistence contract for tenant DB connections.
type ConnectionRepository interface {
	Create(ctx context.Context, c *DBConnection) error
	GetByID(ctx context.Context, id string) (*DBConnection, error)
	GetDefaultForCompany(ctx context.Context, companyID string) (*DBConnection, error)
	ListByCompany(ctx context.Context, companyID string) ([]*DBConnection, error)
	Update(ctx context.Context, c *DBConnection) error
	Delete(ctx context.Context, id string) error
	SetDefault(ctx context.Context, companyID, connectionID string) error
}
