#!/usr/bin/env node
/**
 * Generates packages/api-types/src from the Go structs that cross the `/api`
 * wire (T-02b).
 *
 *   node scripts/generate.mjs            regenerate and write
 *   node scripts/generate.mjs --check    regenerate, compare, write nothing
 *
 * `make types` runs the first; CI runs it and then diffs, so a Go struct
 * change without a regeneration is a red build. The `--check` mode exists for
 * the same reason it does in packages/design-tokens: a developer wants to know
 * whether they are stale without dirtying their tree.
 *
 * tygo does the parsing. What this script adds is two rules and a barrel:
 *
 *  1. **Go interfaces are dropped.** tygo renders `type ThreadRepository
 *     interface{…}` as `export type ThreadRepository = any`, and there are 23
 *     of those in `internal/domain`. A repository is not a wire type — it has
 *     no JSON form at all — and exporting its name bound to `any` hands a
 *     caller a plausible-looking type that silently disables type checking.
 *  2. **`any` becomes `unknown`.** The remaining ones come from Go's
 *     `map[string]interface{}`, whose honest TypeScript is
 *     `Record<string, unknown>`: the value is real, and the caller must narrow
 *     it before use. `any` says the opposite.
 *
 * Both rules run on emitted code only. A comment that happens to contain the
 * word "any" is left alone — the sentence "there is no \"any authenticated
 * key\" tier" is in `domain/api_key.go` and a blunt replace would rewrite it.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Pinned rather than @latest: this writes committed files that CI diffs, so a
// new tygo release must be a deliberate commit rather than something that
// happens to whoever regenerates next.
const TYGO = "github.com/gzuidhof/tygo@v0.2.21";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const srcDir = join(pkgRoot, "src");
// tygo resolves package paths through the Go module, so it has to run there.
const backend = resolve(pkgRoot, "../../apps/backend");

const check = process.argv.includes("--check");

/** The files tygo writes, in the order the barrel re-exports them. */
const GENERATED = ["domain.ts", "events.ts", "api.ts", "videoplan.ts", "webhooks.ts"];

/** Everything but the webhook envelopes and the video plan — see tygo.yaml. */
const BARRELLED = ["domain.ts", "events.ts", "api.ts"];

const BARREL = `/* eslint-disable */
// Code generated by packages/api-types. DO NOT EDIT.
//
// The Go structs the dashboard reads off \`/api\`. Regenerate with \`make types\`.
//
// Inbound webhook envelopes (apps/backend/pkg/models) are deliberately absent:
// no browser ever receives one, and \`models.Message\` would collide with
// \`domain.Message\`. Import them from "@argentum/api-types/webhooks".
//
// The video plan (internal/report/videoplan) is absent for the same reason and
// a sharper one: its \`Brand\`, \`Table\` and \`Metrics\` are names a dashboard
// namespace should not be handed. Import it from
// "@argentum/api-types/videoplan".

${BARRELLED.map((f) => `export * from "./${f.replace(/\.ts$/, ".js")}";`).join("\n")}
`;

function snapshot() {
  const before = new Map();
  let names = [];
  try {
    names = readdirSync(srcDir);
  } catch {
    mkdirSync(srcDir, { recursive: true });
  }
  for (const name of names) {
    before.set(name, readFileSync(join(srcDir, name), "utf8"));
  }
  return before;
}

function runTygo() {
  execFileSync("go", ["run", TYGO, "generate", "--config", "tygo.yaml"], {
    cwd: backend,
    stdio: ["ignore", "inherit", "inherit"],
  });
}

/**
 * Applies the two rules above.
 *
 * The comment attached to a dropped alias goes with it: leaving
 * "ThreadRepository is the persistence contract for conversation threads."
 * floating above an unrelated interface is worse than losing it, and it is
 * still in the Go file where it belongs.
 */
function postProcess(source) {
  const lines = source.split("\n");
  const out = [];
  let inBlockComment = false;

  for (const line of lines) {
    const isCommentLine = inBlockComment || /^\s*(\/\/|\/\*|\*)/.test(line);
    if (/^\s*\/\*/.test(line) && !/\*\//.test(line)) inBlockComment = true;
    else if (inBlockComment && /\*\//.test(line)) inBlockComment = false;

    if (/^export type \w+ = any;$/.test(line)) {
      // Drop the alias, then walk back over the doc comment that introduced it.
      while (out.length) {
        const prev = out[out.length - 1];
        if (/^\s*(\/\*\*?|\*|\*\/|\/\/)/.test(prev)) {
          out.pop();
          continue;
        }
        break;
      }
      continue;
    }

    out.push(isCommentLine ? line : line.replace(/: any\b/g, ": unknown"));
  }

  // Collapse the runs of blank lines a removal can leave behind, and end with
  // exactly one newline.
  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

const before = snapshot();
runTygo();

const after = new Map();
for (const name of GENERATED) {
  const path = join(srcDir, name);
  after.set(name, postProcess(readFileSync(path, "utf8")));
}
after.set("index.ts", BARREL);

const stale = [...after.entries()].filter(([name, body]) => before.get(name) !== body);

if (check) {
  // Put the tree back exactly as it was: --check promises to write nothing,
  // and tygo has already written the raw output over the committed files.
  for (const [name, body] of before) writeFileSync(join(srcDir, name), body);
  if (stale.length) {
    console.error(
      `api-types: ${stale.length} file(s) differ from the Go structs: ${stale
        .map(([name]) => name)
        .join(", ")}\nRun 'make types' and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`api-types: ${GENERATED.length + 1} generated files are current`);
} else {
  for (const [name, body] of after) writeFileSync(join(srcDir, name), body);
  const label = stale.length ? `${stale.length} changed` : "no changes";
  console.log(`api-types: wrote ${after.size} files to src/ (${label})`);
}
