// Package sample is the fixed document the branding preview renders.
//
// It lives here rather than in the HTTP handler because what it must show is a
// rendering question: every element a tenant's branding reaches. If the preview
// omitted the section rules, a customer would approve a colour they had only
// seen on a cover, then find it on eleven headings they never looked at.
package sample

import (
	"time"

	"github.com/fauzanebd/argentum/internal/report/spec"
)

// Document builds the preview spec. genAt is stamped into it rather than read
// from the clock so that two previews of the same branding are the same bytes —
// which is what lets the dashboard cache one and what makes a golden test of
// this package possible.
//
// The figures are invented and say so: a preview carrying plausible-looking
// revenue is a preview somebody eventually forwards as if it were a report.
func Document(genAt time.Time, currency, locale string) *spec.Document {
	pct := func(v float64) *float64 { return &v }
	no := false

	return &spec.Document{
		SpecVersion: 2,
		Format:      "pdf",
		Filename:    "branding-preview.pdf",
		Title:       "Branding preview",
		Currency:    currency,
		Locale:      locale,
		GeneratedAt: genAt.Format(time.RFC3339),
		Meta: spec.Meta{
			Subject:  "Sample report showing how your branding is applied",
			Keywords: "preview, branding",
		},
		Content: spec.Content{Sections: []spec.Section{
			{
				Type:            "cover",
				Text:            "Branding preview",
				Subtitle:        "Every element your branding reaches, on one page",
				Period:          "SAMPLE DOCUMENT",
				PreparedFor:     "Your board",
				Confidentiality: "",
			},
			{Type: "heading", Text: "How this document is branded", Level: 1},
			{Type: "paragraph", Text: "The mark at the top of this page and in the running " +
				"header is your logo when you have uploaded one, and your company name set in " +
				"your accent colour when you have not. The rule under each section heading, the " +
				"period line on the cover and the wordmark all take the accent colour."},
			{
				Type: "callout",
				Tone: "info",
				Text: "The figures below are invented and are here only to show table and " +
					"KPI styling. Nothing in this document came from your data.",
			},
			{
				Type: "kpi_row",
				Items: []spec.Item{
					{Label: "Sample revenue", Value: &spec.Cell{V: 1284000000, Fmt: "currency"}, DeltaPct: pct(12.4)},
					{Label: "Sample orders", Value: &spec.Cell{V: 3480, Fmt: "number"}, DeltaPct: pct(4.1)},
					{Label: "Sample refunds", Value: &spec.Cell{V: 21400000, Fmt: "currency"},
						DeltaPct: pct(2.8), HigherIsBetter: &no},
				},
			},
			{Type: "heading", Text: "Charts keep the verified palette", Level: 1},
			{Type: "paragraph", Text: "Chart series are not recoloured from your accent. The " +
				"palette is checked as a set for greyscale printing and colour-vision " +
				"deficiency, and substituting one colour into it would void that check " +
				"without saying so."},
			{
				Type: "chart",
				Chart: &spec.Chart{
					Type:   "bar",
					Title:  "Sample monthly figures",
					Labels: []string{"Jan", "Feb", "Mar", "Apr", "May", "Jun"},
					Series: []spec.Series{{
						Name:   "Sample",
						Values: []float64{182000000, 196000000, 174000000, 221000000, 208000000, 244000000},
					}},
					Fmt: "currency",
				},
			},
			{Type: "heading", Text: "Tables", Level: 1},
			{
				Type:    "table",
				Caption: "Invented rows, formatted by the renderer rather than by the model",
				Columns: []spec.Column{
					{Label: "Region", Fmt: "text"},
					{Label: "Sample revenue", Fmt: "currency", Align: "right"},
					{Label: "Share", Fmt: "percent", Align: "right"},
				},
				Rows: [][]spec.Cell{
					{{V: "North"}, {V: 486000000}, {V: 37.8}},
					{{V: "South"}, {V: 401000000}, {V: 31.2}},
					{{V: "East"}, {V: 254000000}, {V: 19.8}},
					{{V: "West"}, {V: 143000000}, {V: 11.2}},
				},
				TotalRow: []spec.Cell{{V: "Total"}, {V: 1284000000}, {V: 100}},
			},
			{Type: "footnote", Text: "Sample document generated by Argentum for branding " +
				"preview. The footer line, the confidentiality label and whether the Argentum " +
				"credit appears are all set in Settings → Reports."},
		}},
	}
}
