// Code generated by packages/design-tokens. DO NOT EDIT.
//
// Source:     packages/design-tokens/tokens.json
// Regenerate: make tokens   (CI fails on drift)

package theme

// Brand colours. Light palette only — a document has no dark mode.
var (
	// ColorBackground — Page ground. Large fills, PDF page background.
	ColorBackground = Color{R: 0xFA, G: 0xFA, B: 0xFB} // #FAFAFB

	// ColorSurface — Cards, table bands — anything that sits on the background.
	ColorSurface = Color{R: 0xFF, G: 0xFF, B: 0xFF} // #FFFFFF

	// ColorSurfaceMuted — Hover fill and alternating table rows: one rung under the page.
	ColorSurfaceMuted = Color{R: 0xF4, G: 0xF5, B: 0xF6} // #F4F5F6

	// ColorSurfaceSubtle — Recessed ground: disabled controls, table header band, callout
	// backgrounds.
	ColorSurfaceSubtle = Color{R: 0xF1, G: 0xF2, B: 0xF3} // #F1F2F3

	// ColorPrimary — Brand accent. Rules, KPI emphasis, focus ring, chart series 1.
	ColorPrimary = Color{R: 0xF2, G: 0x5C, B: 0x5C} // #F25C5C

	// ColorPrimaryForeground — Text and icons on a primary fill.
	ColorPrimaryForeground = Color{R: 0xFF, G: 0xFF, B: 0xFF} // #FFFFFF

	// ColorForeground — Body text. Not #000 — a true black on a light ground is a contrast
	// the eye reads as a shadow.
	ColorForeground = Color{R: 0x1F, G: 0x21, B: 0x24} // #1F2124

	// ColorMuted — Secondary text: captions, footers, page numbers, chart axis labels.
	ColorMuted = Color{R: 0x62, G: 0x65, B: 0x6B} // #62656B

	// ColorBorder — Hairlines, table rules, card borders.
	ColorBorder = Color{R: 0xEC, G: 0xED, B: 0xEF} // #ECEDEF

	// ColorDestructive — Errors and negative deltas.
	ColorDestructive = Color{R: 0xE3, G: 0x47, B: 0x4C} // #E3474C

	// ColorDestructiveForeground — Text on a destructive fill.
	ColorDestructiveForeground = Color{R: 0xFF, G: 0xFF, B: 0xFF} // #FFFFFF

	// ColorPositive — Good news: a delta moving the way the reader wants, a `good`
	// callout, an action that executed.
	ColorPositive = Color{R: 0x18, G: 0x9A, B: 0x4D} // #189A4D

	// ColorWarning — A caveat that is not an error: a `warn` callout, a proposal awaiting
	// a decision.
	ColorWarning = Color{R: 0xEF, G: 0x72, B: 0x0C} // #EF720C

	// ColorInfo — Neutral emphasis: an `info` callout, the default tone.
	ColorInfo = Color{R: 0x1C, G: 0x3A, B: 0x62} // #1C3A62
)

// Font families as registered with maroto. See fonts.go for the faces.
const (
	// FontDisplay (Space Grotesk) — Titles, headings, KPI values.
	FontDisplay = "space-grotesk"

	// FontBody (Space Grotesk) — Body copy, table cells.
	FontBody = "space-grotesk"

	// FontMedium (Space Grotesk) — Table headers and labels. A separate maroto family
	// because maroto's style set is normal/bold/italic only — there is no weight axis to
	// put 500 on.
	FontMedium = "space-grotesk-medium"
)

// RadiusBase is the corner radius in millimetres — the print equivalent of the
// dashboard's 0.5rem. Cards, callouts, KPI tiles.
const RadiusBase = 2.12

// TypeScale is the print type scale, in points.
var TypeScale = TypeScaleTokens{
	// Display — Cover title.
	Display: 24,

	// H1 — Section heading.
	H1: 16,

	// H2 — Sub-heading, table title.
	H2: 13,

	// Body — Body copy, table cells.
	Body: 10,

	// Caption — Footer, page numbers, chart axis labels, callout meta.
	Caption: 8,
}

// Spacing is the vertical rhythm, in millimetres.
var Spacing = SpacingTokens{
	// XS — Cell padding, tight gaps.
	XS: 2,

	// SM — Between a heading and its paragraph.
	SM: 4,

	// MD — Between paragraphs and table rows.
	MD: 6,

	// LG — Between sections.
	LG: 10,

	// XL — Cover-page blocks, above a chart.
	XL: 16,
}

// Page is the page geometry, in millimetres.
var Page = PageTokens{
	// Width — A4 page width.
	Width: 210,

	// Height — A4 page height.
	Height: 297,

	// Margin — All four page margins.
	Margin: 18,

	// HeaderHeight — Running header band.
	HeaderHeight: 12,

	// FooterHeight — Running footer band.
	FooterHeight: 10,

	// TableHeaderHeight — Table header row.
	TableHeaderHeight: 8,

	// TableRowHeight — Table body row.
	TableRowHeight: 7,

	// Hairline — Table rules and dividers. Below ~0.15mm a rule disappears on an office
	// laser printer.
	Hairline: 0.2,
}

// ChartPalette is the categorical series palette, ordered by series index. Every entry
// sits on a rung of a CIE L* ladder so the palette survives a black-and-white printer
// and deuteranopia; tokens.json states the method.
var ChartPalette = []Color{
	{R: 0xF2, G: 0x5C, B: 0x5C}, // #F25C5C · series 1 — brand red · L* 59.3
	{R: 0x1C, G: 0x3A, B: 0x62}, // #1C3A62 · series 2 — navy · L* 24.2
	{R: 0xEA, G: 0xAA, B: 0x3E}, // #EAAA3E · series 3 — amber · L* 73.9
	{R: 0x2E, G: 0x7E, B: 0x71}, // #2E7E71 · series 4 — teal · L* 47.9
	{R: 0x77, G: 0x4C, B: 0x96}, // #774C96 · series 5 — purple · L* 40.1
	{R: 0xCA, G: 0xCC, B: 0xD1}, // #CACCD1 · series 6 — grey · L* 82.0
	{R: 0x71, G: 0x3F, B: 0x1C}, // #713F1C · series 7 — brown · L* 32.1
	{R: 0x5C, G: 0xA8, B: 0xE0}, // #5CA8E0 · series 8 — azure · L* 66.3
}
