// Loads tokens.json and answers the only two questions the generators ask of
// it: what is in a group, and does this platform get to see it.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const PKG_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
export const REPO_ROOT = dirname(dirname(PKG_ROOT));
export const TOKENS_PATH = join(PKG_ROOT, 'tokens.json');

export function loadTokens() {
  return JSON.parse(readFileSync(TOKENS_PATH, 'utf8'));
}

/**
 * Entries of a token group that the given platform ("web" | "print") sees.
 *
 * Scope resolves per entry, falling back to the group's `$scope`, defaulting to
 * "all". Keys starting with `$` are documentation and never returned.
 *
 * @returns {Array<[string, object]>} insertion-ordered [name, token] pairs
 */
export function groupEntries(tokens, group, platform) {
  const g = tokens[group];
  if (!g) throw new Error(`tokens.json: no group ${JSON.stringify(group)}`);
  const groupScope = g.$scope ?? 'all';
  return Object.entries(g)
    .filter(([name]) => !name.startsWith('$'))
    .filter(([, tok]) => visible(tok.scope ?? groupScope, platform));
}

/** Group-level visibility, for groups that are a single list or a whole unit. */
export function groupVisible(tokens, group, platform) {
  const g = tokens[group];
  if (!g) throw new Error(`tokens.json: no group ${JSON.stringify(group)}`);
  return visible(g.$scope ?? 'all', platform);
}

function visible(scope, platform) {
  if (scope === 'all') return true;
  if (scope === 'web' || scope === 'print') return scope === platform;
  throw new Error(`tokens.json: unknown scope ${JSON.stringify(scope)}`);
}

/** camelCase → PascalCase, for Go identifiers. */
export function pascal(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** camelCase → kebab-case, for CSS custom property names. */
export function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/**
 * The banner every generated file carries, prefixed for that file's comment
 * syntax ("//" for Go, " *" inside a CSS block comment).
 */
export function banner(commentPrefix) {
  return [
    'Code generated by packages/design-tokens. DO NOT EDIT.',
    '',
    'Source:     packages/design-tokens/tokens.json',
    'Regenerate: make tokens   (CI fails on drift)',
  ]
    .map((line) => (line ? `${commentPrefix} ${line}` : commentPrefix))
    .join('\n');
}
