// Code generated by packages/design-tokens. DO NOT EDIT.
//
// Source:     packages/design-tokens/tokens.json
// Regenerate: make tokens   (CI fails on drift)

/** The design system's colours, for the two places with no plan to read. */
export const TOKEN_COLOR = {
  /** Page background (cream). Large fills, PDF page background. */
  background: "#F5F5F0",
  /** Cards, inputs, table bands — anything that sits on the background. */
  surface: "#FFFFFF",
  /** Slightly darker cream: hover states, alternating table rows. */
  surfaceMuted: "#F1F1EF",
  /** Quietest fill: disabled controls, table header band, callout backgrounds. */
  surfaceSubtle: "#ECECEA",
  /** Brand accent. Rules, KPI emphasis, focus ring, chart series 1. */
  primary: "#F25C5C",
  /** Text and icons on a primary fill. */
  primaryForeground: "#FFFFFF",
  /** Body text. */
  foreground: "#0A0A0A",
  /** Secondary text: captions, footers, page numbers, chart axis labels. */
  muted: "#6B6B6B",
  /** Hairlines, table rules, card borders. */
  border: "#E2E2DC",
  /** Errors and negative deltas. */
  destructive: "#EF4343",
  /** Text on a destructive fill. */
  destructiveForeground: "#FFFFFF",
  /** Good news: a delta moving the way the reader wants, a `good` callout. */
  positive: "#3F7A46",
  /** A caveat that is not an error: a `warn` callout. */
  warning: "#B07A16",
  /** Neutral emphasis: an `info` callout, the default tone. */
  info: "#1C3A62",
  /** Sidebar background — matches the chat composer, not the page cream. */
  sidebarSurface: "#FFFFFF",
  /** Sidebar text. */
  sidebarForeground: "#262626",
  /** Sidebar hover fill. */
  sidebarAccent: "#E7E7E4",
  /** Sidebar text on a hover fill. */
  sidebarAccentForeground: "#1A1A1A",
} as const;

/**
 * The brand block a plan carries, with no tenant to fill it.
 *
 * Mirrors videoplan.builder.brand() field for field, so Remotion Studio and
 * the validation-failure frame show what an unbranded tenant would get
 * rather than an approximation somebody typed.
 */
export const DEFAULT_BRAND_COLORS = {
  primary: TOKEN_COLOR.primary,
  primary_on_dark: TOKEN_COLOR.primary,
  foreground: TOKEN_COLOR.foreground,
  background: TOKEN_COLOR.background,
  muted: TOKEN_COLOR.muted,
  border: TOKEN_COLOR.border,
  dark: TOKEN_COLOR.foreground,
  on_dark: TOKEN_COLOR.background,
  surface: TOKEN_COLOR.surface,
  surface_subtle: TOKEN_COLOR.surfaceSubtle,
  positive: TOKEN_COLOR.positive,
  destructive: TOKEN_COLOR.destructive,
} as const;
