/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This document, as JSON
         * @description Public and keyless: an integrator reads the contract before they have a
         *     credential to call it with. It is the same bytes as
         *     `apps/backend/openapi/v1.yaml`, converted to JSON.
         *
         *     It is still behind the `/v1` kill switch. A spec for a surface that is
         *     refusing every call would generate a client nobody can use, so a
         *     disabled deployment answers 503 here too.
         */
        get: operations["getOpenAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The key, its scopes, its rate limit, and the tenant's credit position
         * @description The first call to make and the one paste that makes a support question
         *     answerable. It needs no scope — a key with none must still be able to
         *     find out that it has none.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a document from a spec
         * @description Deterministic. A spec goes in, a file comes out, and nothing about it
         *     touches an LLM or a thread.
         *
         *     **`Accept` decides the response body.** `application/json` (or an absent
         *     `Accept`) returns the document object with a short-lived presigned URL.
         *     The format's own content type — `application/pdf`, `text/csv`, the two
         *     OOXML types — or `application/octet-stream` returns the bytes inline,
         *     which is what a caller writing them straight to disk wants.
         *
         *     A spec that outruns the synchronous window becomes a job and answers
         *     `202` with a report object, on the same shape `POST /v1/reports`
         *     returns. Write one collection path for both.
         */
        post: operations["renderReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask an agent for a report
         * @description A prompt in, a real agent turn behind it, a document at the end. Seconds
         *     to minutes, priced in tokens.
         *
         *     Three ways to collect the result, and a caller picks one: poll
         *     `GET /v1/reports/{id}`, stream `GET /v1/reports/{id}/events`, or supply
         *     a `callback_url` and verify the signature described by
         *     `GET /v1/me`'s `webhooks` block.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a report
         * @description Once `status` is `completed` the `document` block carries a freshly
         *     presigned `download_url`. It is re-issued on every read rather than
         *     stored, so a caller who saved one and came back an hour later gets a
         *     working link without paying to regenerate the document.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a report's progress
         * @description Server-sent events for a job that can take minutes. Two event names:
         *     `progress` while the agent works, and `report` — terminal — carrying the
         *     same object `GET /v1/reports/{id}` returns.
         *
         *     The agent's token deltas are deliberately not forwarded: a report's
         *     consumer wants progress and a file, not the prose of an answer they
         *     asked for as a PDF.
         *
         *     A job that had already finished when the caller connected gets its
         *     `report` frame and nothing else. A queued *render* job has no thread to
         *     publish on, so it gets the same — poll that one.
         */
        get: operations["streamReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List generated documents
         * @description Newest first, cursor-paginated.
         *
         *     **No download URLs on the list.** Presigning is a signature per row, and
         *     a caller paging a hundred documents to find one is not about to fetch
         *     all hundred. `GET /v1/documents/{id}` issues the URL for the one they
         *     picked.
         */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one document's metadata and a fresh download URL */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a document's bytes
         * @description Streams the object rather than redirecting to the presigned URL. A
         *     server-side HTTP client that does not follow redirects — a deliberate
         *     setting in plenty of them — would otherwise write three hundred bytes of
         *     nothing to disk, and the redirect is a second hostname the caller's
         *     egress rules have to allow.
         */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question
         * @description **`Accept` decides the door.** `text/event-stream` streams the turn as
         *     it is written; anything else blocks until the turn answers.
         *
         *     A client disconnect never cancels a turn: the agent runs in the worker
         *     and this route is a reader of the same bus the dashboard reads. Hanging
         *     up ends the read, the turn finishes, the answer persists, and
         *     `GET /v1/threads/{id}/messages` collects it.
         *
         *     The synchronous door answers **504** when the turn outruns the wait —
         *     not when the turn fails. That response carries `in_flight.thread_id`,
         *     and it **keeps its idempotency key**, so the retry a 504 invites replays
         *     instead of starting a second billed turn. Attach to
         *     `GET /v1/threads/{id}/events` instead.
         */
        post: operations["sendChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the conversations this integration started
         * @description `api` threads only. A machine credential that could list the dashboard's
         *     threads would let a leaked key read the staff's own chat history.
         */
        get: operations["listThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one conversation */
        get: operations["getThread"];
        put?: never;
        post?: never;
        /**
         * Delete a conversation
         * @description `write:chat` rather than `read:threads`: destroying a conversation is
         *     not a read. Saved dashboards the turns produced are removed with it.
         */
        delete: operations["deleteThread"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a transcript
         * @description Oldest first, cursor-paginated.
         */
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attach to a thread's newest turn
         * @description The resume door. A 504 from the synchronous send and a
         *     `409 request_in_flight` from a retried one both hand back a `thread_id`,
         *     and neither is collectable by re-POSTing — one turn is already running,
         *     and starting a second is what the whole idempotency chain exists to
         *     prevent. This is where a caller goes instead.
         *
         *     If the thread's newest turn has already answered, the answer is
         *     delivered and the stream closes. Send `Last-Event-ID` to have the
         *     messages you missed replayed first.
         */
        get: operations["streamThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Switch on `type`. `code` is the specific reason within that class, and
         *     only `message` is meant for a human to read.
         */
        ErrorDetail: {
            /**
             * @description The coarse class. The vocabulary is closed.
             * @enum {string}
             */
            type: "invalid_request" | "authentication" | "permission" | "not_found" | "rate_limit" | "budget_exhausted" | "server";
            /**
             * @description The specific reason — `insufficient_scope`, `spec_too_large`,
             *     `thread_not_found`, and so on. New codes are added over time; treat
             *     an unknown one as its `type`.
             * @example insufficient_scope
             */
            code: string;
            /** @description A sentence for a person. Do not switch on it. */
            message: string;
            /**
             * @description The field or header that was wrong, when there is one. Its presence
             *     means something — an integrator reading `"param": "rows"` fixes
             *     their request without reading prose.
             */
            param?: string;
            /** @description The same value as the `X-Request-Id` header. */
            request_id?: string;
        };
        /**
         * @description Every failure under `/v1` has this shape. A bare `{"error": "…"}` string
         *     anywhere here is a defect.
         */
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description A 409. `in_flight` is present only for `request_in_flight`, and its
         *     contents are whatever ids identify the work — `{thread_id, run_id,
         *     started_at}` for a chat turn, `{report_id, status}` for a report.
         */
        ConflictError: {
            error: components["schemas"]["ErrorDetail"];
            /** @description The ids of the request that is still running. */
            in_flight?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description `credits` is absent when this deployment cannot read a balance, and
         *     `webhooks` only appears for a key carrying `write:reports` — a read-only
         *     key has no callback to verify and no reason to hold the secret.
         */
        Me: {
            /**
             * @description The contract version, as a date. It matches `info.version` in this
             *     document.
             * @example 2026-07-28
             */
            api_version: string;
            company: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            key: {
                id: string;
                /** @description The label chosen when the key was minted. */
                name: string;
                scopes: components["schemas"]["Scope"][];
            };
            rate_limit: {
                requests_per_minute: number;
            };
            credits?: components["schemas"]["Credits"];
            webhooks?: components["schemas"]["WebhookSettings"];
        };
        /**
         * @description `enforced: false` means nothing was consulted. It is not a zero balance
         *     — reporting `$0.00` there would read as "you are out of credit", which
         *     is the opposite of what an unenforced deployment is saying. A tenant on
         *     their own LLM key reports `byo_llm: true` and no balance.
         */
        Credits: {
            enforced: boolean;
            byo_llm?: boolean;
            /**
             * @description The verdict the budget check reached.
             * @example ok
             */
            status?: string;
            /** @description Dollars, not the micro-USD the system counts in — this number is read by a person. */
            balance_usd?: number;
            grant_usd?: number;
            remaining_pct?: number;
        };
        /** @description The signing secret for `callback_url` deliveries, minted on first read. */
        WebhookSettings: {
            /** @example whsec_… */
            signing_secret: string;
            /** @example Argentum-Signature */
            signature_header: string;
            /** @description How to verify, in one sentence, so it travels with the secret. */
            how: string;
        };
        /**
         * @description One capability a key may carry. Fixed at mint time.
         * @enum {string}
         */
        Scope: "read:metrics" | "read:threads" | "read:usage" | "read:audit" | "read:documents" | "write:chat" | "write:actions" | "write:reports";
        /** @enum {string} */
        DocumentFormat: "pdf" | "pptx" | "xlsx" | "csv";
        /** @description One generated file. */
        Document: {
            /** Format: uuid */
            id: string;
            /** @constant */
            object: "document";
            filename: string;
            format: components["schemas"]["DocumentFormat"];
            size_bytes: number;
            /**
             * @description Which door produced it. `api` for either `/v1` report route, `agent`
             *     for the `generate_document` tool inside a dashboard turn.
             * @enum {string}
             */
            source: "agent" | "api";
            /**
             * Format: uuid
             * @description Absent for a document the render door produced — it has no
             *     conversation behind it.
             */
            thread_id?: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: uri
             * @description Presigned and short-lived, re-issued on every read rather than
             *     stored. Absent on list responses and when the object store could not
             *     be reached.
             */
            download_url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        /** @description What the render door returns when `Accept` asks for JSON. */
        RenderedDocument: {
            /** @constant */
            object: "document";
            document: components["schemas"]["Document"];
            request_id?: string;
        };
        DocumentPage: {
            data: components["schemas"]["Document"][];
            /**
             * @description Not `len(data) == limit`. A caller cannot tell a full last page from
             *     a full middle one, and asking for one more page to find out is a
             *     request nobody should have to make.
             */
            has_more: boolean;
            next_cursor?: string;
        };
        /**
         * @description Send `user_ref` **or** `thread_id`: the first names who the report is
         *     for, the second continues a conversation that already knows.
         */
        CreateReportRequest: {
            /**
             * @description What the report should contain, in words.
             * @example Monthly revenue for 2024 with a bar chart by month and a short commentary.
             */
            prompt: string;
            /** @description Defaults to `pdf`. */
            format?: components["schemas"]["DocumentFormat"];
            /**
             * @description Your own identifier for the person this is on behalf of. It is what
             *     makes the spend attributable in the tenant's usage reporting.
             */
            user_ref?: string;
            /**
             * Format: uuid
             * @description Continue an existing `api` conversation instead of starting one.
             */
            thread_id?: string;
            /**
             * Format: uri
             * @description Receives the signed `report.completed` body. Optional — most callers
             *     poll or stream. A private-network target is refused unless the
             *     deployment allows one.
             */
            callback_url?: string;
            /** @description `id` or `en`. Decides separators, month names and magnitude words. */
            locale?: string;
            /** @description An ISO 4217 code. */
            currency?: string;
        };
        /**
         * @description One shape for both doors and for the poll route, so a caller writes the
         *     collection path once whether the job came from a prompt or from a spec
         *     that ran long.
         */
        Report: {
            /** Format: uuid */
            id: string;
            /** @constant */
            object: "report";
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            /**
             * @description `agentic` for a prompt; `render` for a spec that outran the synchronous window.
             * @enum {string}
             */
            kind: "agentic" | "render";
            format: components["schemas"]["DocumentFormat"];
            /**
             * Format: uuid
             * @description The conversation behind an agentic report — continue it through
             *     `POST /v1/chat`. Absent for a render job, which has none.
             */
            thread_id?: string;
            document?: components["schemas"]["Document"];
            /** @description Why a `failed` report failed. */
            error?: string;
            /** Format: date-time */
            created_at: string;
            request_id?: string;
        };
        /**
         * @description Send `user_ref` **or** `thread_id`. `user_ref` keys the thread when there
         *     is no `thread_id`, and is what makes the spend attributable.
         */
        ChatRequest: {
            /** @description The question you want answered. */
            message: string;
            /**
             * Format: uuid
             * @description Continue a conversation you are already tracking.
             */
            thread_id?: string;
            /** @description Your own identifier for the person asking. */
            user_ref?: string;
        };
        /**
         * @description One question and its answer. The same shape arrives as the `final` SSE
         *     frame, so a caller who starts on the synchronous door and moves to the
         *     stream does not rewrite their parser.
         */
        Turn: {
            /** @constant */
            object: "turn";
            /** Format: uuid */
            thread_id: string;
            /**
             * @description Identifies this turn within the thread. It is the id of the question
             *     that started it.
             */
            run_id?: string;
            message: components["schemas"]["Message"];
            usage?: components["schemas"]["Usage"];
            request_id?: string;
        };
        /**
         * @description What this turn cost. Best-effort and omitted entirely rather than
         *     reported as zeros: an all-zero window happens when attaching to a turn
         *     that had already finished, and publishing `tokens_in: 0` there would
         *     state something false about a turn that cost real money.
         */
        Usage: {
            tokens_in: number;
            tokens_out: number;
            /** @description Dollars, for the reason `credits` gives. */
            cost_usd: number;
        };
        /**
         * @description One turn in a transcript. Token counts and latency are deliberately not
         *     here: they are per-message zeros for every streamed turn, and a field
         *     that is honestly zero most of the time is a field integrators report as
         *     a bug.
         */
        Message: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            object: "message";
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            created_at?: string;
        };
        MessagePage: {
            data: components["schemas"]["Message"][];
            has_more: boolean;
            next_cursor?: string;
        };
        /**
         * @description A conversation. Deliberately not the internal thread record, which
         *     carries a phone number, a Discord user id and two Lark keys — none of
         *     which an `api` thread has, and all of which would become part of a
         *     published contract the moment one was serialized.
         */
        Thread: {
            /** Format: uuid */
            id: string;
            /** @constant */
            object: "thread";
            user_ref?: string;
            title?: string;
            /** @description The rolling topic summary the thread resolver keeps. */
            summary?: string;
            /** Format: date-time */
            last_message_at: string;
            /** Format: date-time */
            created_at: string;
        };
        ThreadPage: {
            data: components["schemas"]["Thread"][];
            has_more: boolean;
            next_cursor?: string;
        };
        /**
         * @description The 504 body. The field names match the `409 request_in_flight` on
         *     purpose: both mean "the work is still running and here is how to find
         *     it", and a caller should be able to parse them with one branch.
         */
        PendingTurn: {
            error: components["schemas"]["ErrorDetail"];
            in_flight: {
                /** Format: uuid */
                thread_id: string;
                run_id?: string;
                /** Format: date-time */
                started_at: string;
            };
        };
        /**
         * @description One frame of a chat stream, as the `data:` of an SSE event whose
         *     `event:` is the `type` below. The names are the dashboard's, unchanged,
         *     because one worker publishes both surfaces.
         *
         *     `final` and `error` are terminal. `message` appears only on a resumed
         *     stream, replaying what a disconnect missed. Only `message` and `final`
         *     carry an `id:` — they are the frames backed by something persisted.
         *
         *     Treat an unknown event name as ignorable; that is what lets this list
         *     grow without breaking you.
         */
        ChatEvent: components["schemas"]["ChatEventStarted"] | components["schemas"]["ChatEventDelta"] | components["schemas"]["ChatEventThinking"] | components["schemas"]["ChatEventTool"] | components["schemas"]["ChatEventMessage"] | components["schemas"]["ChatEventError"] | components["schemas"]["ChatEventFinal"];
        /**
         * started
         * @description The worker picked the turn up.
         */
        ChatEventStarted: {
            /** Format: uuid */
            thread_id: string;
            run_id?: string;
            /** Format: date-time */
            at: string;
        };
        /**
         * delta
         * @description A fragment of the answer as it is written. Never persisted; carries no `id:`.
         */
        ChatEventDelta: {
            content: string;
        };
        /**
         * thinking
         * @description A one-line statement of what the agent is doing.
         */
        ChatEventThinking: {
            step: string;
        };
        /**
         * tool_call / tool_result
         * @description The tool's **name only** — never its arguments or its result. Those
         *     carry the SQL the agent ran, and the place for that is the audit log,
         *     where it is redacted on the way in and reachable only by an admin.
         */
        ChatEventTool: {
            /** @example run_sql */
            tool?: string;
        };
        /**
         * message
         * @description A persisted message being replayed to a client that reconnected with
         *     `Last-Event-ID`. Carries an `id:`.
         */
        ChatEventMessage: components["schemas"]["Message"];
        /**
         * error
         * @description The turn failed. Terminal.
         */
        ChatEventError: {
            message: string;
        };
        /**
         * final
         * @description The answer, as the same `Turn` object the synchronous door returns.
         *     Terminal, and carries an `id:` a client can resume from.
         */
        ChatEventFinal: components["schemas"]["Turn"];
        /**
         * @description One frame of a report stream. `progress` while the agent works, `report`
         *     — terminal — carrying the same object the poll route returns, and
         *     `error` when the stream itself could not be opened.
         */
        ReportEvent: components["schemas"]["ReportEventProgress"] | components["schemas"]["ReportEventReport"] | components["schemas"]["ChatEventError"];
        /**
         * progress
         * @description What is happening, not what the agent is saying.
         */
        ReportEventProgress: {
            /** @enum {string} */
            type: "started" | "tool_call" | "tool_result" | "thinking";
            /** Format: date-time */
            at: string;
            tool?: string;
            step?: string;
        };
        /**
         * report
         * @description The terminal frame. Identical to `GET /v1/reports/{id}`.
         */
        ReportEventReport: components["schemas"]["Report"];
        /**
         * @description One file, one format, one content tree.
         *
         *     `content` carries one of three shapes: `sections` for a PDF or a deck,
         *     `table` for a CSV, `sheets` or `table` for a workbook.
         */
        ReportSpec: {
            /**
             * @description `2` for the enterprise layout — cover page, running header, footer.
             *     Absent or `1` renders flat. A v1 spec is a v2 spec whose columns are
             *     all text, so this only decides whether the *renderer* offers the v2
             *     chrome: a document that has been rendering as a bare table for three
             *     months should not sprout a cover page because the backend was
             *     upgraded.
             * @enum {integer}
             */
            spec_version?: 1 | 2;
            format: components["schemas"]["DocumentFormat"];
            /** @description Without a directory. Sanitised; the extension follows `format`. */
            filename?: string;
            title?: string;
            /** @description `id` or `en`. Empty derives it from `currency`. */
            locale?: string;
            /** @description An ISO 4217 code. Empty uses the company default. */
            currency?: string;
            /**
             * @description RFC3339. It is a spec field rather than a clock read so the same
             *     spec renders the same bytes twice — pin it and the output is
             *     reproducible.
             */
            generated_at?: string;
            meta?: components["schemas"]["ReportSpecMeta"];
            content: components["schemas"]["ReportSpecContent"];
        };
        /**
         * @description What lands in the PDF's info dictionary. A document that leaves the
         *     building with an empty Title in its properties is one a records system
         *     cannot file.
         */
        ReportSpecMeta: {
            author?: string;
            subject?: string;
            keywords?: string;
        };
        ReportSpecContent: {
            sections?: components["schemas"]["ReportSpecSection"][];
            table?: components["schemas"]["ReportSpecTable"];
            sheets?: components["schemas"]["ReportSpecSheet"][];
        };
        /**
         * @description One block in the document flow. Every payload field for every section
         *     type is on this one object rather than in a union — a model that puts
         *     `text` on a callout instead of inside it still renders something.
         */
        ReportSpecSection: {
            /** @enum {string} */
            type: "cover" | "heading" | "paragraph" | "kpi_row" | "table" | "callout" | "key_value" | "chart" | "footnote" | "page_break" | "spacer";
            subtitle?: string;
            period?: string;
            prepared_for?: string;
            prepared_by?: string;
            confidentiality?: string;
            text?: string;
            /** @description Heading level, 1–3. */
            level?: number;
            title?: string;
            /**
             * @description A callout's colour.
             * @enum {string}
             */
            tone?: "info" | "warn" | "good";
            items?: components["schemas"]["ReportSpecItem"][];
            columns?: components["schemas"]["ReportSpecColumn"][];
            rows?: components["schemas"]["ReportSpecCell"][][];
            total_row?: components["schemas"]["ReportSpecCell"][];
            caption?: string;
            /** @description A v1 spacer's height in millimetres. */
            size?: number;
            chart?: components["schemas"]["ReportSpecChart"];
        };
        /**
         * @description A row of a `key_value` block or a card in a `kpi_row`. Both vocabularies
         *     are accepted — `{k, v}` and `{label, value}` — because rendering nothing
         *     when a caller picked the wrong pair of field names is not a defensible
         *     failure.
         */
        ReportSpecItem: {
            k?: string;
            v?: string;
            label?: string;
            value?: components["schemas"]["ReportSpecCell"];
            /** @description Percent units: `12.5` is +12.5%, not +1250%. */
            delta_pct?: number;
            /**
             * @description Empty reads the direction off the sign of `delta_pct`.
             * @enum {string}
             */
            direction?: "up" | "down" | "increase" | "decrease" | "rising" | "falling" | "naik" | "turun";
            /**
             * @description Whether an up arrow is good news. Defaults to true. Churn going up is
             *     not good news, and a renderer that colours every rise green is
             *     telling the reader something false.
             */
            higher_is_better?: boolean;
            fmt?: string;
        };
        /**
         * @description A header plus the formatting every cell beneath it inherits. A bare
         *     string is accepted as `{label: "…"}` — that is the whole of the v1 table
         *     shim.
         */
        ReportSpecColumn: string | {
            label: string;
            /**
             * @description Empty infers the kind from the column's own values.
             * @enum {string}
             */
            fmt?: "text" | "number" | "currency" | "percent" | "date";
            /**
             * @description Empty lets the kind decide — numerics right, everything else left.
             * @enum {string}
             */
            align?: "left" | "center" | "right";
            /**
             * @description Rarely needed: the renderer measures the header and a sample of
             *     the cells.
             */
            width_weight?: number;
        };
        /**
         * @description One value, optionally with a format override. A scalar is accepted as
         *     `{v: <scalar>}`.
         *
         *     Numbers are decoded without going through a float, so a 19-digit invoice
         *     number survives the trip — a float64 loses its last four digits and
         *     would print a subtly wrong id in a document someone pays against.
         */
        ReportSpecCell: (string | number | boolean | null) | {
            v?: string | number | boolean | null;
            /** @enum {string} */
            fmt?: "text" | "number" | "currency" | "percent" | "date";
        };
        ReportSpecTable: {
            columns: components["schemas"]["ReportSpecColumn"][];
            rows: components["schemas"]["ReportSpecCell"][][];
            total_row?: components["schemas"]["ReportSpecCell"][];
            caption?: string;
        };
        /** @description One workbook tab. */
        ReportSpecSheet: {
            name: string;
            columns: components["schemas"]["ReportSpecColumn"][];
            rows: components["schemas"]["ReportSpecCell"][][];
        };
        /**
         * @description There is no `stacked` flag: stacking is a chart type. A flag would make
         *     `{type: "pie", stacked: true}` expressible, and every such combination is
         *     a validation rule someone has to write, test and explain.
         */
        ReportSpecChart: {
            /** @enum {string} */
            type?: "line" | "bar" | "grouped_bar" | "stacked_bar" | "pie" | "donut" | "sparkline";
            title?: string;
            labels?: string[];
            series?: components["schemas"]["ReportSpecSeries"][];
            fmt?: string;
            y_axis?: components["schemas"]["ReportSpecAxis"];
            /**
             * @description Zero takes the renderer's default, which is almost always right: the
             *     width is the measure and the height is a proportion of it.
             */
            height_mm?: number;
        };
        /**
         * @description One plotted population. For a pie or a donut only the first series is
         *     drawn, because a pie of two series is two pies.
         */
        ReportSpecSeries: {
            name?: string;
            values?: number[];
        };
        /**
         * @description `min` matters more than it looks: a bar chart whose axis starts at 94% of
         *     the smallest bar shows a 3% movement as a doubling, which is the most
         *     common way a correct number is used to say something false.
         */
        ReportSpecAxis: {
            label?: string;
            min?: number;
            max?: number;
        };
    };
    responses: {
        /**
         * @description The request is malformed. `error.param` names the offending field
         *     whenever there is one to name.
         */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No key, or one that is not usable. One message covers malformed,
         *     unknown, wrong-secret, revoked and expired: a caller holding a broken
         *     credential has no business learning which of the five it is.
         */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A valid key without the scope this route requires. Scopes are fixed when
         *     a key is minted — mint a new one.
         */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such resource **for this company**. A cross-tenant id and a
         *     nonexistent id answer identically; anything else is an existence oracle
         *     over another company's data.
         */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Two shapes, distinguished by `error.code`. `request_in_flight` carries
         *     `in_flight` with the ids of the work already running;
         *     `idempotency_key_reuse` means the same key arrived with a different
         *     body.
         */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                "Idempotent-Replay": components["headers"]["Idempotent-Replay"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConflictError"];
            };
        };
        /**
         * @description The tenant is out of credit. Typed rather than a 500 on purpose: a
         *     programmatic caller retries a 500, and retrying a turn nobody can pay
         *     for is a loop that stops only when someone notices.
         */
        BudgetExhausted: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is over this deployment's cap. */
        TooLarge: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests on this key. */
        RateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                "Retry-After": components["headers"]["Retry-After"];
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Our fault. Quote `error.request_id` — it is the string that finds this
         *     attempt in our logs.
         */
        ServerError: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Either the whole public API is switched off (`api_disabled`, with
         *     `Retry-After`) or one subsystem this route needs is not configured on
         *     this deployment. The routes exist and are coming back, which is why this
         *     is not a 404.
         */
        Unavailable: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Page size. A value over the repository's cap is clamped rather than
         *     refused — a caller asking for 10 000 rows wants as many as they can get,
         *     and the cursor is what makes the rest reachable.
         */
        Limit: number;
        /**
         * @description The `next_cursor` from the previous page. Opaque: it encodes the
         *     `(created_at, id)` of the last row you saw, and hand-building one is a
         *     `400`, not a silent restart at page one.
         */
        Cursor: string;
        /** @description A report id. */
        ReportID: string;
        /** @description A document id. */
        DocumentID: string;
        /** @description A thread id. */
        ThreadID: string;
        /**
         * @description When present, the thread must belong to this end user or the route
         *     answers 404. We cannot authenticate a `user_ref` — a key belongs to the
         *     company, not to one of its users — but we can hold a caller to the one
         *     they named, which is what turns "our backend passes the logged-in user's
         *     id through" into an isolation boundary rather than a convention.
         */
        UserRefGuard: string;
        /**
         * @description A unique string per logical request; a UUID is the usual choice. Both
         *     SDKs generate one automatically when you do not supply it.
         *
         *     A second request under the same key ends one of three ways:
         *
         *     * the original finished — you get its result again, with
         *       `Idempotent-Replay: true`, and nothing is billed twice;
         *     * the original is still running — `409 request_in_flight`, carrying the
         *       ids of the work you are already waiting on;
         *     * the body differs from the original's — `409 idempotency_key_reuse`.
         *       Use a new key for a new request.
         *
         *     A request that fails forgets its key, so a retry after a 500 is a fresh
         *     attempt. The one exception is `POST /v1/chat`'s 504, where the request
         *     failed and the work did not.
         */
        IdempotencyKeyRequired: string;
        /**
         * @description The `id:` of the last frame you received. An SSE client sends this by
         *     itself on reconnect. The messages after that point are replayed before
         *     the stream attaches live. A value this API did not issue is a `400`.
         */
        LastEventID: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description This request's id, on every response including failures. Send your own
         *     and it is echoed back, provided it is at most 128 characters of
         *     `[A-Za-z0-9_.:-]`.
         */
        "X-Request-Id": string;
        /** @description Requests permitted per minute on this key. */
        "RateLimit-Limit": number;
        /** @description Whole requests left in the bucket after this one. */
        "RateLimit-Remaining": number;
        /** @description Seconds until at least one request is available. `0` means now. */
        "RateLimit-Reset": number;
        /** @description Seconds to wait before retrying. Both SDKs honour it. */
        "Retry-After": number;
        /**
         * @description `true` when this response replays an earlier request under the same
         *     `Idempotency-Key` rather than executing a new one.
         */
        "Idempotent-Replay": "true";
        /** @description `attachment; filename="…"`, with the generated filename. */
        "Content-Disposition": string;
        /**
         * @description The document's id, on the inline-bytes path. It is the only place the id
         *     appears when the body is a file rather than JSON.
         */
        "X-Document-Id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 document. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own identity and budget. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    renderReport: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A unique string per logical request; a UUID is the usual choice. Both
                 *     SDKs generate one automatically when you do not supply it.
                 *
                 *     A second request under the same key ends one of three ways:
                 *
                 *     * the original finished — you get its result again, with
                 *       `Idempotent-Replay: true`, and nothing is billed twice;
                 *     * the original is still running — `409 request_in_flight`, carrying the
                 *       ids of the work you are already waiting on;
                 *     * the body differs from the original's — `409 idempotency_key_reuse`.
                 *       Use a new key for a new request.
                 *
                 *     A request that fails forgets its key, so a retry after a 500 is a fresh
                 *     attempt. The one exception is `POST /v1/chat`'s 504, where the request
                 *     failed and the work did not.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "spec_version": 2,
                 *       "format": "pdf",
                 *       "title": "Revenue by month",
                 *       "locale": "en",
                 *       "currency": "USD",
                 *       "content": {
                 *         "sections": [
                 *           {
                 *             "type": "heading",
                 *             "text": "Revenue by month"
                 *           },
                 *           {
                 *             "type": "kpi_row",
                 *             "items": [
                 *               {
                 *                 "label": "Total",
                 *                 "value": {
                 *                   "v": 270300,
                 *                   "fmt": "currency"
                 *                 },
                 *                 "delta_pct": 10.5
                 *               }
                 *             ]
                 *           },
                 *           {
                 *             "type": "table",
                 *             "columns": [
                 *               {
                 *                 "label": "Month"
                 *               },
                 *               {
                 *                 "label": "Revenue",
                 *                 "fmt": "currency"
                 *               }
                 *             ],
                 *             "rows": [
                 *               [
                 *                 "July",
                 *                 128400
                 *               ],
                 *               [
                 *                 "August",
                 *                 141900
                 *               ]
                 *             ],
                 *             "total_row": [
                 *               {
                 *                 "v": "Total"
                 *               },
                 *               {
                 *                 "v": 270300,
                 *                 "fmt": "currency"
                 *               }
                 *             ]
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ReportSpec"];
            };
        };
        responses: {
            /**
             * @description The rendered document. The body is JSON or the file's bytes,
             *     according to `Accept`.
             */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "Idempotent-Replay": components["headers"]["Idempotent-Replay"];
                    "Content-Disposition": components["headers"]["Content-Disposition"];
                    "X-Document-Id": components["headers"]["X-Document-Id"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderedDocument"];
                    "application/pdf": string;
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation": string;
                    "application/octet-stream": string;
                };
            };
            /**
             * @description The spec outran the synchronous window and became a job. Poll
             *     `GET /v1/reports/{id}` or stream `GET /v1/reports/{id}/events`.
             */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "Idempotent-Replay": components["headers"]["Idempotent-Replay"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A unique string per logical request; a UUID is the usual choice. Both
                 *     SDKs generate one automatically when you do not supply it.
                 *
                 *     A second request under the same key ends one of three ways:
                 *
                 *     * the original finished — you get its result again, with
                 *       `Idempotent-Replay: true`, and nothing is billed twice;
                 *     * the original is still running — `409 request_in_flight`, carrying the
                 *       ids of the work you are already waiting on;
                 *     * the body differs from the original's — `409 idempotency_key_reuse`.
                 *       Use a new key for a new request.
                 *
                 *     A request that fails forgets its key, so a retry after a 500 is a fresh
                 *     attempt. The one exception is `POST /v1/chat`'s 504, where the request
                 *     failed and the work did not.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "prompt": "Monthly revenue for 2024, with a bar chart by month and a short commentary.",
                 *       "format": "pdf",
                 *       "user_ref": "u_42"
                 *     }
                 */
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description The job was accepted. It is `queued` until a worker picks it up. */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "Idempotent-Replay": components["headers"]["Idempotent-Replay"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["BudgetExhausted"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A report id. */
                id: components["parameters"]["ReportID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report, and its document once there is one. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    streamReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A report id. */
                id: components["parameters"]["ReportID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream that closes on the terminal `report` frame. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ReportEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /**
                 * @description Page size. A value over the repository's cap is clamped rather than
                 *     refused — a caller asking for 10 000 rows wants as many as they can get,
                 *     and the cursor is what makes the rest reachable.
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description The `next_cursor` from the previous page. Opaque: it encodes the
                 *     `(created_at, id)` of the last row you saw, and hand-building one is a
                 *     `400`, not a silent restart at page one.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Only documents of this format. */
                format?: components["schemas"]["DocumentFormat"];
                /** @description Only documents created at or after this RFC3339 timestamp. */
                created_after?: string;
                /** @description Only documents created at or before this RFC3339 timestamp. */
                created_before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of documents. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A document id. */
                id: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The document. `download_url` is absent when the object store could
             *     not be reached — the metadata is still true, and a caller listing
             *     documents is not necessarily about to download one.
             */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A document id. */
                id: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "Content-Disposition": components["headers"]["Content-Disposition"];
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "text/csv": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation": string;
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    sendChat: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A unique string per logical request; a UUID is the usual choice. Both
                 *     SDKs generate one automatically when you do not supply it.
                 *
                 *     A second request under the same key ends one of three ways:
                 *
                 *     * the original finished — you get its result again, with
                 *       `Idempotent-Replay: true`, and nothing is billed twice;
                 *     * the original is still running — `409 request_in_flight`, carrying the
                 *       ids of the work you are already waiting on;
                 *     * the body differs from the original's — `409 idempotency_key_reuse`.
                 *       Use a new key for a new request.
                 *
                 *     A request that fails forgets its key, so a retry after a 500 is a fresh
                 *     attempt. The one exception is `POST /v1/chat`'s 504, where the request
                 *     failed and the work did not.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /**
                 * @description The `id:` of the last frame you received. An SSE client sends this by
                 *     itself on reconnect. The messages after that point are replayed before
                 *     the stream attaches live. A value this API did not issue is a `400`.
                 */
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "message": "What were total sales last month?",
                 *       "user_ref": "u_42"
                 *     }
                 */
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /**
             * @description The completed turn, or — with `Accept: text/event-stream` — the
             *     stream that produces it.
             */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    "Idempotent-Replay": components["headers"]["Idempotent-Replay"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Turn"];
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["BudgetExhausted"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
            /**
             * @description The **wait** ran out, not the turn. It is still running and still
             *     being billed; collect it from the stream rather than asking again.
             */
            504: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingTurn"];
                };
            };
        };
    };
    listThreads: {
        parameters: {
            query?: {
                /**
                 * @description Page size. A value over the repository's cap is clamped rather than
                 *     refused — a caller asking for 10 000 rows wants as many as they can get,
                 *     and the cursor is what makes the rest reachable.
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description The `next_cursor` from the previous page. Opaque: it encodes the
                 *     `(created_at, id)` of the last row you saw, and hand-building one is a
                 *     `400`, not a silent restart at page one.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Only threads belonging to this end user. */
                user_ref?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of threads, newest first. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getThread: {
        parameters: {
            query?: {
                /**
                 * @description When present, the thread must belong to this end user or the route
                 *     answers 404. We cannot authenticate a `user_ref` — a key belongs to the
                 *     company, not to one of its users — but we can hold a caller to the one
                 *     they named, which is what turns "our backend passes the logged-in user's
                 *     id through" into an isolation boundary rather than a convention.
                 */
                user_ref?: components["parameters"]["UserRefGuard"];
            };
            header?: never;
            path: {
                /** @description A thread id. */
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thread. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteThread: {
        parameters: {
            query?: {
                /**
                 * @description When present, the thread must belong to this end user or the route
                 *     answers 404. We cannot authenticate a `user_ref` — a key belongs to the
                 *     company, not to one of its users — but we can hold a caller to the one
                 *     they named, which is what turns "our backend passes the logged-in user's
                 *     id through" into an isolation boundary rather than a convention.
                 */
                user_ref?: components["parameters"]["UserRefGuard"];
            };
            header?: never;
            path: {
                /** @description A thread id. */
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /**
                 * @description Page size. A value over the repository's cap is clamped rather than
                 *     refused — a caller asking for 10 000 rows wants as many as they can get,
                 *     and the cursor is what makes the rest reachable.
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description The `next_cursor` from the previous page. Opaque: it encodes the
                 *     `(created_at, id)` of the last row you saw, and hand-building one is a
                 *     `400`, not a silent restart at page one.
                 */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description When present, the thread must belong to this end user or the route
                 *     answers 404. We cannot authenticate a `user_ref` — a key belongs to the
                 *     company, not to one of its users — but we can hold a caller to the one
                 *     they named, which is what turns "our backend passes the logged-in user's
                 *     id through" into an isolation boundary rather than a convention.
                 */
                user_ref?: components["parameters"]["UserRefGuard"];
            };
            header?: never;
            path: {
                /** @description A thread id. */
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of messages. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
    streamThread: {
        parameters: {
            query?: {
                /**
                 * @description When present, the thread must belong to this end user or the route
                 *     answers 404. We cannot authenticate a `user_ref` — a key belongs to the
                 *     company, not to one of its users — but we can hold a caller to the one
                 *     they named, which is what turns "our backend passes the logged-in user's
                 *     id through" into an isolation boundary rather than a convention.
                 */
                user_ref?: components["parameters"]["UserRefGuard"];
            };
            header?: {
                /**
                 * @description The `id:` of the last frame you received. An SSE client sends this by
                 *     itself on reconnect. The messages after that point are replayed before
                 *     the stream attaches live. A value this API did not issue is a `400`.
                 */
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path: {
                /** @description A thread id. */
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream that closes on `final` or `error`. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
            503: components["responses"]["Unavailable"];
        };
    };
}
