// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// `/api` response bodies that are not domain entities, from
// apps/backend/internal/transport/http/handlers/wire.go.
import type { BudgetState } from "./events.js";
import type {
  Agent,
  AgentChannelBinding,
  APIKey,
  APIKeyRequestStats,
  APIRequestError,
  Channel,
  CompanyProfile,
  MCPServer,
  MCPTransport,
  MetricDefinition,
  MetricGrain,
  MetricUnit,
} from "./domain.js";

//////////
// source: wire.go

/**
 * AgentToolInfo is one tool checkbox in Settings → Agents (T-S1).
 * Name comes from the live registry, so a tool added on the backend appears in
 * the dashboard without a frontend change. Label does not: a tool's own
 * Description is prompt text written for the model — three sentences of
 * instruction on when to call it — and pasting that beside a checkbox would be
 * unreadable. An unlabelled tool falls back to its bare name rather than
 * disappearing, which is the failure direction a per-agent allowlist can
 * afford.
 */
export interface AgentToolInfo {
  name: string;
  label: string;
}
/**
 * AgentsResponse is the body of `GET /api/agents`.
 * The tool vocabulary rides along with the roster rather than sitting on its
 * own route: it is only ever read by the same form, and `GET /api/agents/tools`
 * beside `GET /api/agents/:id` is a static segment competing with a wildcard in
 * one method tree. Templates ride along for both reasons and a third — the chat
 * reads the same payload to find a thread's starter questions, so a separate
 * route would be a second request on a screen that already has the answer.
 */
export interface AgentsResponse {
  agents: (Agent | undefined)[];
  tools: AgentToolInfo[];
  /**
   * Templates is the create-an-agent gallery (T-B3), already narrowed to the
   * tools this deployment runs. Empty on a deployment that loaded no gallery,
   * which the dashboard renders as the blank form and nothing else — the
   * product as it was before the templates existed.
   */
  templates: AgentTemplate[];
  /**
   * Generation is whether the create form may offer "Generate with AI"
   * (T-B4), and why not when it may not.
   */
  generation: AgentGenerationInfo;
}
/**
 * AgentGenerationInfo is the state of the Generate button before it is pressed
 * (T-B4).
 * Two booleans rather than one, because "this deployment has no generator" and
 * "this workspace has no credit left" are different sentences and only the
 * second is the tenant's to act on. Both leave the form perfectly able to save
 * an agent — generation is a shortcut past the empty textarea, never the way in.
 */
export interface AgentGenerationInfo {
  available: boolean;
  credits_exhausted: boolean;
}
/**
 * AgentGenerationResult is the body of `POST /api/agents/generate` (T-B4): the
 * two fields, improved, for the tenant to review in the form.
 * Nothing was written when this was produced. The agent row changes when the
 * tenant presses Save and not before, which is what makes regenerating and
 * undoing free.
 */
export interface AgentGenerationResult {
  description: string;
  persona: string;
  /**
   * Fallback names what happened when the generated persona was rejected by
   * the output validator: "template" when the picked card's persona came back
   * instead, "input" when the tenant's own text did, and empty when the model
   * wrote what is above. The dashboard says so — a tenant about to save this
   * text should know whether a model wrote it.
   */
  fallback?: string;
}
/**
 * AgentTemplate is one gallery card in Settings → Agents (T-B3).
 * A projection of agenttemplates.Template rather than the loader's own struct,
 * for the same reason AgentToolInfo is not a tools.Tool: the config type is a
 * YAML shape that the file's authors may extend — an editorial note, an ordering
 * hint, a card we ship but do not offer yet — and every field of it would reach
 * the browser the day it was added. This is the published half, and it is a
 * deliberate list.
 */
export interface AgentTemplate {
  key: string;
  name: string;
  description: string;
  /**
   * Persona prefills the instructions field. It is sent to the browser
   * because the tenant edits it before saving — nothing about a template is
   * applied behind the form.
   */
  persona: string;
  suggested_tools: string[];
  /**
   * SourceHints pre-tick likely databases in the create form, matched against
   * a connection's label and description. The dashboard shows which hint
   * matched, because a silently pre-ticked source scopes an agent away from
   * its own data.
   */
  source_hints: string[];
  /**
   * StarterQuestions are offered on a new conversation opened on an agent
   * created from this template.
   */
  starter_questions: string[];
}
/**
 * AgentBindingsResponse is the body of `GET /api/agent-bindings` (T-S4).
 * Channels rides along for the same reason AgentsResponse carries the tool
 * vocabulary: it is the vocabulary the form beside the table has to offer, and
 * it is the backend that decides which channels can be bound at all — a
 * frontend array would have to be edited the day a fifth channel is added, and
 * nothing would report that it had not been.
 */
export interface AgentBindingsResponse {
  bindings: (AgentChannelBinding | undefined)[];
  channels: Channel[];
}
/**
 * CompanyProfileResponse is the body of `GET|PUT /api/company/profile` (T-B1).
 * RenderedBlock rides along because a prompt fragment the tenant cannot read is
 * a prompt fragment they cannot debug: the form takes four fields and the model
 * reads one composed string, and the only way "this is what your agent sees" is
 * true is if the backend that composes it also returns it.
 * Profile is present even when the company has no row — an empty form with the
 * defaults, so the dashboard renders one shape rather than two.
 */
export interface CompanyProfileResponse {
  profile?: CompanyProfile;
  /**
   * Exists distinguishes "never filled in" from "filled in and then
   * emptied". The dashboard uses it to decide between a prompt to describe
   * the business and a saved-but-blank state.
   */
  exists: boolean;
  rendered_block: string;
  /**
   * Truncated is true when the block hit the cap. The UI says so; the turn
   * carries the shortened text either way.
   */
  truncated: boolean;
  /**
   * BlockTokenLimit is the cap in tokens, echoed rather than duplicated in the
   * frontend — the number is a backend policy and the warning beside the
   * textarea should not have its own copy of it.
   */
  block_token_limit: number /* int */;
}
/**
 * ProfileSuggestionResponse is the body of `GET /api/company/profile/suggestion`
 * (T-B2): what the connected sources say the business is, before anybody has
 * agreed to it.
 * Draft is nil when there is nothing to review, which is the ordinary state of
 * a company that has just signed up — the panel is absent rather than empty.
 * The two counters beside it are what let the panel explain the absence instead
 * of leaving a tenant to guess whether the feature is broken.
 */
export interface ProfileSuggestionResponse {
  draft?: CompanyProfile;
  /**
   * Sources is how many connected sources have been described.
   */
  sources: number /* int */;
  /**
   * CreditsExhausted says the balance is why there is no draft. Adding a
   * source never fails for credit, so without this the tenant sees silence.
   */
  credits_exhausted: boolean;
  /**
   * RenderedBlock is the draft as the agent would read it, composed by the
   * same code the turn uses — so what a tenant approves is what they saw.
   */
  rendered_block?: string;
  truncated: boolean;
}
/**
 * APIKeysResponse is the body of `GET /api/api-keys` (T-13, extended by T-A5).
 * Stats rides with the roster for the same reason AgentsResponse carries the
 * tool vocabulary: the tab never renders one without the other, and a key's
 * traffic is a property of that key rather than a separate resource.
 * Keyed by key id rather than sorted alongside `Keys`, because a key with no
 * traffic in the window has no entry at all — "no calls" and "no such key" are
 * different facts, and a parallel array would have to invent a zero row to keep
 * the indices lined up.
 */
export interface APIKeysResponse {
  keys: (APIKey | undefined)[];
  /**
   * Stats is absent on a deployment without the request recorder, and after a
   * failed counters read. A tab that hides the numbers still manages keys.
   */
  stats?: { [key: string]: APIKeyRequestStats | undefined};
}
/**
 * APIKeyErrorsResponse is the body of `GET /api/api-keys/errors` (T-A5) — the
 * last non-2xx `/v1` responses, newest first, optionally for one key.
 */
export interface APIKeyErrorsResponse {
  errors: (APIRequestError | undefined)[];
  /**
   * Limit is echoed so the tab can say "the last 50" without hardcoding the
   * number the backend actually applied.
   */
  limit: number /* int */;
}
/**
 * SendMessageResponse is the body of `POST /api/chat` — the acknowledgement
 * that a turn was queued, not the answer. The answer arrives over the
 * WebSocket as a stream of app.ChatEvent.
 */
export interface SendMessageResponse {
  /**
   * TaskID is the asynq task. It is returned for support and for tests;
   * nothing in the dashboard routes on it.
   */
  task_id: string;
  thread_id: string;
  /**
   * IsNewThread tells the dashboard to add a row to the thread list rather
   * than move an existing one to the top.
   */
  is_new_thread: boolean;
  user_msg_id: string;
  /**
   * BudgetWarning is present only when the turn ran *and* the tenant is near
   * the end of their credit. Its absence is the ordinary case and is the
   * signal — a client must not read `verdict === "ok"`, because in the
   * ordinary case there is no object to read it from.
   */
  budget_warning?: BudgetState;
}
/**
 * MCPServersResponse is the body of `GET /api/mcp-servers` (T-M1).
 * Transports rides along for the reason AgentsResponse carries the tool
 * vocabulary: which transports this release speaks is a backend fact, and a
 * frontend `["http", "sse"]` would be the array nobody edits the day a third
 * one is added — or, worse, the array somebody adds "stdio" to, which is a
 * decision the backend has made and will not revisit.
 */
export interface MCPServersResponse {
  servers: (MCPServer | undefined)[];
  transports: MCPTransport[];
  /**
   * AllowsInsecureHTTP is whether this deployment accepts a plaintext http
   * URL. The form's hint is written from it, because "must be https" printed
   * beside a deployment that accepts http is a sentence that costs an admin a
   * support ticket — and the reverse is worse.
   */
  allows_insecure_http: boolean;
}
/**
 * MCPServerResponse is one server and the tools discovery found on it — the
 * shape every write route answers with, so a browser never holds two views of
 * the same server.
 */
export interface MCPServerResponse {
  server?: MCPServer;
  tools: MCPToolView[];
}
/**
 * MCPToolView is one discovered tool plus the fact a browser cannot compute.
 * Drifted means an approved tool's description or argument schema has changed
 * since the admin approved it. It is the cheapest injection vector this track
 * opens — a description is text that enters the agent's context — so it is
 * surfaced rather than silently adopted, which is locked decision 6 arriving in
 * the UI.
 * The fields are spelled out rather than embedded: Go would promote them onto
 * the wire either way, but `packages/api-types` is generated from these
 * declarations and an embedded pointer generates `MCPServerTool?: unknown`,
 * which is a browser type that describes nothing.
 */
export interface MCPToolView {
  id: string;
  server_id: string;
  tool_name: string;
  description: string;
  input_schema: unknown;
  read_only: boolean;
  approved: boolean;
  drifted: boolean;
  discovered_at: string;
}
/**
 * MetricsResponse is the body of `GET /api/metrics` (T-06).
 * Grains and Units ride along for the same reason MCPServersResponse carries
 * Transports: which values this release understands is a backend fact, and a
 * frontend that hard-codes the dropdown is the one that goes stale the day a
 * grain is added — or wrong the day the backend's list and the form's disagree.
 */
export interface MetricsResponse {
  metrics: (MetricDefinition | undefined)[];
  grains: MetricGrain[];
  units: MetricUnit[];
}
/**
 * MetricResponse is one metric — the shape every write route answers with.
 */
export interface MetricResponse {
  metric?: MetricDefinition;
}
/**
 * MetricTestResponse is what the "Test" button shows: the rendered SQL and the
 * number it returned over the validation window, without saving anything (T-06).
 */
export interface MetricTestResponse {
  value: number /* float64 */;
  from: string;
  to: string;
  rendered_sql: string;
}
