// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// `/api` response bodies that are not domain entities, from
// apps/backend/internal/transport/http/handlers/wire.go.
import type { BudgetState } from "./events.js";
import type { Agent } from "./domain.js";

//////////
// source: wire.go

/**
 * AgentToolInfo is one tool checkbox in Settings → Agents (T-S1).
 * Name comes from the live registry, so a tool added on the backend appears in
 * the dashboard without a frontend change. Label does not: a tool's own
 * Description is prompt text written for the model — three sentences of
 * instruction on when to call it — and pasting that beside a checkbox would be
 * unreadable. An unlabelled tool falls back to its bare name rather than
 * disappearing, which is the failure direction a per-agent allowlist can
 * afford.
 */
export interface AgentToolInfo {
  name: string;
  label: string;
}
/**
 * AgentsResponse is the body of `GET /api/agents`.
 * The tool vocabulary rides along with the roster rather than sitting on its
 * own route: it is only ever read by the same form, and `GET /api/agents/tools`
 * beside `GET /api/agents/:id` is a static segment competing with a wildcard in
 * one method tree.
 */
export interface AgentsResponse {
  agents: (Agent | undefined)[];
  tools: AgentToolInfo[];
}
/**
 * SendMessageResponse is the body of `POST /api/chat` — the acknowledgement
 * that a turn was queued, not the answer. The answer arrives over the
 * WebSocket as a stream of app.ChatEvent.
 */
export interface SendMessageResponse {
  /**
   * TaskID is the asynq task. It is returned for support and for tests;
   * nothing in the dashboard routes on it.
   */
  task_id: string;
  thread_id: string;
  /**
   * IsNewThread tells the dashboard to add a row to the thread list rather
   * than move an existing one to the top.
   */
  is_new_thread: boolean;
  user_msg_id: string;
  /**
   * BudgetWarning is present only when the turn ran *and* the tenant is near
   * the end of their credit. Its absence is the ordinary case and is the
   * signal — a client must not read `verdict === "ok"`, because in the
   * ordinary case there is no object to read it from.
   */
  budget_warning?: BudgetState;
}
