// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// `/api` response bodies that are not domain entities, from
// apps/backend/internal/transport/http/handlers/wire.go.
import type { BudgetState } from "./events.js";
import type {
  Agent,
  AgentChannelBinding,
  APIKey,
  APIKeyRequestStats,
  APIRequestError,
  Channel,
} from "./domain.js";

//////////
// source: wire.go

/**
 * AgentToolInfo is one tool checkbox in Settings → Agents (T-S1).
 * Name comes from the live registry, so a tool added on the backend appears in
 * the dashboard without a frontend change. Label does not: a tool's own
 * Description is prompt text written for the model — three sentences of
 * instruction on when to call it — and pasting that beside a checkbox would be
 * unreadable. An unlabelled tool falls back to its bare name rather than
 * disappearing, which is the failure direction a per-agent allowlist can
 * afford.
 */
export interface AgentToolInfo {
  name: string;
  label: string;
}
/**
 * AgentsResponse is the body of `GET /api/agents`.
 * The tool vocabulary rides along with the roster rather than sitting on its
 * own route: it is only ever read by the same form, and `GET /api/agents/tools`
 * beside `GET /api/agents/:id` is a static segment competing with a wildcard in
 * one method tree.
 */
export interface AgentsResponse {
  agents: (Agent | undefined)[];
  tools: AgentToolInfo[];
}
/**
 * AgentBindingsResponse is the body of `GET /api/agent-bindings` (T-S4).
 * Channels rides along for the same reason AgentsResponse carries the tool
 * vocabulary: it is the vocabulary the form beside the table has to offer, and
 * it is the backend that decides which channels can be bound at all — a
 * frontend array would have to be edited the day a fifth channel is added, and
 * nothing would report that it had not been.
 */
export interface AgentBindingsResponse {
  bindings: (AgentChannelBinding | undefined)[];
  channels: Channel[];
}
/**
 * APIKeysResponse is the body of `GET /api/api-keys` (T-13, extended by T-A5).
 * Stats rides with the roster for the same reason AgentsResponse carries the
 * tool vocabulary: the tab never renders one without the other, and a key's
 * traffic is a property of that key rather than a separate resource.
 * Keyed by key id rather than sorted alongside `Keys`, because a key with no
 * traffic in the window has no entry at all — "no calls" and "no such key" are
 * different facts, and a parallel array would have to invent a zero row to keep
 * the indices lined up.
 */
export interface APIKeysResponse {
  keys: (APIKey | undefined)[];
  /**
   * Stats is absent on a deployment without the request recorder, and after a
   * failed counters read. A tab that hides the numbers still manages keys.
   */
  stats?: { [key: string]: APIKeyRequestStats | undefined};
}
/**
 * APIKeyErrorsResponse is the body of `GET /api/api-keys/errors` (T-A5) — the
 * last non-2xx `/v1` responses, newest first, optionally for one key.
 */
export interface APIKeyErrorsResponse {
  errors: (APIRequestError | undefined)[];
  /**
   * Limit is echoed so the tab can say "the last 50" without hardcoding the
   * number the backend actually applied.
   */
  limit: number /* int */;
}
/**
 * SendMessageResponse is the body of `POST /api/chat` — the acknowledgement
 * that a turn was queued, not the answer. The answer arrives over the
 * WebSocket as a stream of app.ChatEvent.
 */
export interface SendMessageResponse {
  /**
   * TaskID is the asynq task. It is returned for support and for tests;
   * nothing in the dashboard routes on it.
   */
  task_id: string;
  thread_id: string;
  /**
   * IsNewThread tells the dashboard to add a row to the thread list rather
   * than move an existing one to the top.
   */
  is_new_thread: boolean;
  user_msg_id: string;
  /**
   * BudgetWarning is present only when the turn ran *and* the tenant is near
   * the end of their credit. Its absence is the ordinary case and is the
   * signal — a client must not read `verdict === "ok"`, because in the
   * ordinary case there is no object to read it from.
   */
  budget_warning?: BudgetState;
}
