// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// The stored dashboard spec and one resolved panel, from
// apps/backend/internal/dashboard/spec. A panel stores a question and a
// column mapping — never values — so everything here describes what to
// ask, and `Resolved` is what came back.

//////////
// source: project.go

/**
 * Resolved is one panel's answer in the shape the browser draws.
 * Values are raw: no formatting, no rounding, no currency symbol. The Fmt the
 * panel carries travels beside them so the browser decides how to write them,
 * which is what keeps a chart label, a table cell and a CSV export from
 * disagreeing about the same number.
 */
export interface Resolved {
  panel_id: string;
  title?: string;
  viz: Viz;
  fmt?: Format;
  /**
   * Charts.
   */
  labels?: string[];
  series?: Series[];
  /**
   * KPI. Pointers, because a KPI over no rows has no value and a zero there is
   * the fabrication T-Q9 exists to stop: "nothing matched" and "the total is
   * nought" are different facts and only one of them is safe to read aloud.
   */
  value?: number /* float64 */;
  comparison?: number /* float64 */;
  delta?: number /* float64 */;
  delta_pct?: number /* float64 */;
  /**
   * Table.
   */
  columns?: string[];
  rows?: { [key: string]: unknown}[];
  row_count: number /* int */;
  /**
   * Truncated says there is more data than the panel drew. SeriesTruncated
   * says there are more *series* than the palette can colour. They are
   * different facts and read differently to a person, so they are two fields.
   */
  truncated?: boolean;
  series_truncated?: boolean;
  note?: string;
  error?: string;
}
/**
 * Series is one line, bar group or slice set. A nil point is a gap in the data,
 * never a zero — a line chart that draws a missing month at the axis is a claim
 * the data does not make.
 */
export interface Series {
  name: string;
  points: (number /* float64 */ | undefined)[];
}

//////////
// source: spec.go
/*
Package spec is the stored shape of a dashboard: what its panels ask, which
columns they read, and which filters bind into them (T-D4).

A panel stores a **question and a column mapping, never values**. That is the
difference between a dashboard and a screenshot, and every rule in this
package follows from it: the SQL carries {{tokens}} rather than dates, the
mapping names columns rather than positions, and a default window is a preset
name rather than two timestamps.

The package is pure — types, validation and projection, no database and no
clock — so the rules are testable without either. Binding and execution are
the parent package's job.
*/

/**
 * Version is the spec version this release writes. It is stored on the row as
 * well as in the JSON so a future reader can branch without parsing first.
 */
export const Version = 1;
/**
 * SeriesCap is the most series a panel may draw.
 * It is not a taste call and must not be re-derived elsewhere: it is the length
 * of the chart palette in packages/design-tokens/tokens.json, and
 * docs/coverage/report-charts.md records what a ninth series does — it wraps
 * onto the first one's red, so two lines in one chart are the same colour and
 * the chart is wrong in a way nobody can see.
 */
export const SeriesCap = 8;
/**
 * Dashboard is the stored spec.
 */
export interface Dashboard {
  spec_version: number /* int */;
  title: string;
  source_id: string; // the default every panel inherits
  filters?: Filter[];
  panels: Panel[];
  refresh_secs?: number /* int */;
  timezone?: string;
}
/**
 * Panel is one tile: a question, where to draw it, and how to read the answer.
 */
export interface Panel {
  id: string; // stable across edits; the cache and the grid key on it
  title?: string;
  viz: Viz;
  layout: Layout;
  /**
   * Exactly one of MetricKey and SQL is set. A kpi panel prefers MetricKey:
   * the registry's number is validated on save and re-checked on every read,
   * and a KPI the agent re-derived is the divergence 039_metric_definitions
   * exists to prevent — two threads, two revenues. Every other viz needs more
   * than one row, which the registry refuses by construction
   * (metric_service.go: maxRows 2), so it carries SQL.
   */
  metric_key?: string;
  sql?: string; // single SELECT, {{tokens}} bound at run time
  map: Mapping;
  fmt?: Format;
}
/**
 * Mapping names the columns a panel reads.
 * Named, never positional: SELECT * reorders the day the tenant adds a column,
 * and a chart whose series silently became a different column draws without
 * complaint and cannot be seen to be wrong.
 */
export interface Mapping {
  label?: string; // x-axis / category column
  series?: string[]; // wide form: month, revenue, cost
  series_by?: string; // long form: month, channel, revenue
  value?: string; // the measure; kpi's number, long form's height
  delta_value?: string; // kpi comparison column
}
/**
 * Layout places a panel on a 12-column grid in integer units.
 */
export interface Layout {
  x: number /* int */;
  y: number /* int */;
  w: number /* int */;
  h: number /* int */;
}
/**
 * GridColumns is the width of the grid a Layout is placed on.
 */
export const GridColumns = 12;
/**
 * Viz is how a panel draws its answer.
 */
export const VizLine = "line";
export const VizBar = "bar";
export const VizGroupedBar = "grouped_bar";
export const VizStackedBar = "stacked_bar";
export const VizPie = "pie";
export const VizDonut = "donut";
export const VizKPI = "kpi";
export const VizTable = "table";
export type Viz = typeof VizLine | typeof VizBar | typeof VizGroupedBar | typeof VizStackedBar | typeof VizPie | typeof VizDonut | typeof VizKPI | typeof VizTable;
/**
 * Format is how a number is written out. It is presentation only: the resolver
 * returns raw values and the browser formats, so a CSV export and a chart label
 * cannot disagree about the underlying number.
 */
export type Format = string;
export const FmtText: Format = "text";
export const FmtNumber: Format = "number";
export const FmtCurrency: Format = "currency";
export const FmtPercent: Format = "percent";
export const FmtDate: Format = "date";
/**
 * Kind is a filter's type, which decides how a request value is coerced before
 * it is bound.
 */
export const KindDateRange = "date_range";
export const KindDate = "date";
export const KindEnum = "enum";
export const KindNumber = "number";
export const KindBool = "bool";
export type Kind = typeof KindDateRange | typeof KindDate | typeof KindEnum | typeof KindNumber | typeof KindBool;
/**
 * Filter declares a parameter the dashboard's panels may bind.
 * Options are a UX affordance and are deliberately **not** enforced against the
 * value a viewer sends. The security boundary is the bound parameter, not the
 * option list: a value outside the set returns no rows, which is the correct
 * outcome. A check here would suggest the check is what makes it safe, and the
 * day somebody adds a kind without one, that belief is what breaks.
 */
export interface Filter {
  name: string; // the {{token}} it binds; a date_range binds two
  label?: string;
  kind: Kind;
  options?: string[]; // enum affordance only
  default?: unknown; // a date_range default is a PRESET NAME
}

//////////
// source: window.go

/**
 * Window is the [From, To) a panel is measured over. Half-open, matching
 * metric.Window, so a template written for one reads correctly under the other.
 */
export interface Window {
  From: string;
  To: string;
}
/**
 * Preset is a named relative window, resolved server-side at request time.
 * **A default is stored as a preset name, never as two timestamps.** That single
 * rule is the whole difference between a live dashboard and a snapshot: two
 * stored timestamps are correct on the day they were saved and wrong every day
 * after, and nothing about the dashboard looks broken while it happens.
 */
export const PresetLast7d = "last_7d";
export const PresetLast30d = "last_30d";
export const PresetMTD = "mtd";
export const PresetQTD = "qtd";
export const PresetYTD = "ytd";
export const PresetLastMonth = "last_month";
export type Preset = typeof PresetLast7d | typeof PresetLast30d | typeof PresetMTD | typeof PresetQTD | typeof PresetYTD | typeof PresetLastMonth;
