// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// What `GET /api/dashboards/:id/data` answers, from
// apps/backend/internal/dashboard.
import type {
  Dashboard as DashboardSpec,
  Resolved,
  Window,
} from "./dashboardspec.js";
import type { Dashboard } from "./domain.js";

//////////
// source: input.go

/**
 * Input is one submitted dashboard, whoever submitted it.
 * It lives here rather than beside the service because internal/app depends on
 * internal/tools and not the other way round, so the create_dashboard tool
 * cannot name a type declared in app. Putting the shape next to the spec it
 * carries keeps one definition for both callers.
 */
export interface Input {
  thread_id?: string;
  title: string;
  description: string;
  spec: DashboardSpec;
}
/**
 * SaveResult carries the stored dashboard, what it counted, and any panel that
 * saved with a warning — so an agent finishing a turn, or an admin in the UI,
 * can say which tiles need a second look without re-reading the row.
 */
export interface SaveResult {
  dashboard?: Dashboard;
  warnings?: PanelWarning[];
  /**
   * RowCount is every row the panels returned when the dashboard was saved.
   * It exists because a data tool that returns a URL and no row count is
   * half-wired: guardrails.CheckFabrication grounds a reply on
   * TurnEvidence.DataRows > 0, and the metric registry's gate recorded what
   * happens when a tool omits it — every metric-only answer was suppressed as
   * a fabrication while the audit row logged rows_returned = NULL.
   */
  row_count: number /* int */;
}
/**
 * PanelWarning is a panel that is structurally sound and did not answer when it
 * was saved.
 */
export interface PanelWarning {
  panel_id: string;
  message: string;
}

//////////
// source: result.go

/**
 * Result is one resolve: every panel's answer, plus what the filters actually
 * resolved to, so the page can say which window it is showing rather than
 * leaving the reader to assume it is the one they picked last week.
 */
export interface Result {
  dashboard_id: string;
  title: string;
  applied_filters?: { [key: string]: string};
  windows?: { [key: string]: Window};
  panels: (Resolved | undefined)[];
  resolved_at: string;
}
