// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// One parsed page, from apps/backend/internal/docparse.

//////////
// source: client.go
/*
Package docparse is the client for `apps/docparse`, the Python service that
reads a PDF's own text layer and says which pages it could not (T-P2).

It is the second outbound dependency this backend has, and it is shaped like
the first (`internal/report/video`) for the reason that package states: a
call into another container fails in ways that mean different things to
whoever reads the message, and collapsing them into "parse failed" throws
away the only information the reader needed.

  - not configured on this deployment;
  - configured and unreachable, or broken;
  - reachable and the document was refused.

The third one is the interesting one here, because a refusal is *terminal*:
a document with 400 pages will have 400 pages on the retry, and a queue that
retries it is a queue that fills with work nobody wants done.

**No page content is ever logged from this package.** The pages are the
tenant's document — a supplier's invoice, a bank statement — and the service
itself is careful about this. A client that logged its response body would
undo that from our side.
*/

/**
 * Document is one parsed file.
 */
export interface Document {
  page_count: number /* int */;
  parser: ParserInfo;
  pages: Page[];
}
/**
 * ParserInfo is which build produced this. Recorded on the artifact and read
 * back by T-P13, for the reason T-Q15 exists: a score that cannot name what
 * produced it cannot be re-run as the same measurement — and a sidecar serving
 * from a previous image looks exactly like a passing run.
 */
export interface ParserInfo {
  name: string;
  version: string;
}
/**
 * KindText means the page's own text layer was read and can be believed.
 */
export const KindText = "text";
/**
 * KindNeedsOCR means it could not: no text, a broken font map, or a scan.
 * T-P3 is what turns these into content, and until it exists they are
 * counted and left empty rather than guessed at.
 */
export const KindNeedsOCR = "needs_ocr";
/**
 * KindFailed is one page that raised while the rest of the document parsed.
 */
export const KindFailed = "failed";
/**
 * KindOCR is a page the text layer could not read and a model did (T-P3).
 * A third state rather than promoting the page to `text`, because the two
 * are not equally trustworthy and every later reader — the reviewer, the
 * eval set, whoever is asked why a figure is wrong — needs to know which
 * one produced a given line.
 */
export const KindOCR = "ocr";
/**
 * Page kinds.
 */
export type Kind = typeof KindText | typeof KindNeedsOCR | typeof KindFailed | typeof KindOCR;
/**
 * Page is what the parser found on one page.
 */
export interface Page {
  page_no: number /* int */;
  kind: string;
  width: number /* float64 */;
  height: number /* float64 */;
  /**
   * CharCount, AlnumRatio and ImageAreaRatio are the three numbers the
   * routing decision was made from. They are carried rather than dropped so
   * that "why was this page sent to OCR?" is answerable from the artifact
   * instead of by re-running the parser.
   */
  char_count: number /* int */;
  alnum_ratio: number /* float64 */;
  image_area_ratio: number /* float64 */;
  markdown: string;
  words: Word[];
  tables: Table[];
  /**
   * HiddenCharCount is how many characters the sidecar dropped as invisible
   * — type below the legibility floor, or type the colour of the page
   * (T-P10). Carried rather than discarded because a page holding two hundred
   * characters nobody can see is a fact a reviewer should be shown, and a
   * hygiene step with no counter is one nobody can prove ran.
   */
  hidden_char_count?: number /* int */;
  error?: string;
}
/**
 * Word is one word and where it sat, in PDF points from the top-left.
 */
export interface Word {
  text: string;
  x0: number /* float64 */;
  top: number /* float64 */;
  x1: number /* float64 */;
  bottom: number /* float64 */;
}
/**
 * Table is a candidate: a grid of strings and the rectangle it came from.
 * Candidate, not table. Whether these rows mean anything — which is the header,
 * what a TOTAL row is, what the numbers are — is T-P4, and whether it becomes
 * data is a person's decision in T-P7.
 */
export interface Table {
  index: number /* int */;
  /**
   * Strategy is `lines` when ruling lines defined the grid and `text` when
   * word alignment did. It reaches the reviewer because the second is an
   * inference: a wrong column boundary looks exactly like a right one until
   * somebody reads the page beside it.
   */
  strategy: string;
  bbox: number /* float64 */[];
  rows: string[][];
  row_count: number /* int */;
  col_count: number /* int */;
}
/**
 * RenderedPage is one page as an image, for the OCR path (T-P3).
 */
export interface RenderedPage {
  page_no: number /* int */;
  dpi: number /* int */;
  /**
   * ContentType and Base64 are what a multimodal model needs as a data URI,
   * and they are kept apart so the caller builds that string rather than this
   * package assuming which provider will read it.
   */
  content_type: string;
  base64: string;
  error?: string;
}
/**
 * Options configures an HTTPParser.
 */
export interface Options {
  /**
   * BaseURL of the parser, e.g. http://argentum-docparse:8091. Empty means
   * this deployment has none.
   */
  BaseURL: string;
  /**
   * Secret is sent as `x-docparse-secret`. Empty matches a service with no
   * secret set, which is the developer-machine configuration.
   */
  Secret: string;
  /**
   * Timeout bounds one whole parse. It sits above the service's own work
   * rather than below it: a parser that is slow on a 200-page scan should
   * answer us, not be cut off mid-answer and reported as unreachable.
   */
  Timeout: unknown /* time.Duration */;
}
/**
 * HTTPParser talks to one parser service.
 */
export interface HTTPParser {
}
