// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// One table extracted from an uploaded PDF, from
// apps/backend/internal/doctable. A draft until a person applies it: the
// review surface reads every field here, and `verify` is what decides
// whether the Apply control is enabled at all.

//////////
// source: continuation.go

/**
 * PageBox is where one page's part of a table sat, in PDF points.
 * A table that spans three pages has three of these, and the review surface
 * (T-P7) needs every one of them: a reviewer checking a joined table against
 * the document has to be shown the three rectangles it was joined from, not the
 * first one three times.
 */
export interface PageBox {
  page: number /* int */;
  bbox?: number /* float64 */[];
}

//////////
// source: doctable.go
/*
Package doctable turns a parser's grid of strings into typed columns (T-P4).

**This is where the accuracy of the whole PDF feature is won or lost, and no
public benchmark scores it.** The parsers in the roadmap's §2 are measured on
how well they render a page as markdown; none of them is measured on whether
the figure that ends up in a database is the figure that was printed. Between
a table candidate and a source sit seven failure families, and six of them
produce a number that is wrong and looks right:

  - locale numerals — "1.234" is one number in Jakarta and another in London;
  - header scale words — "dalam jutaan" makes every cell below it a million;
  - accounting negatives — "(1.234)" is minus one thousand two hundred;
  - footnote markers — "1.234²" is not 1,234 raised to anything;
  - merged headers — two header rows are one column name;
  - continuation — a table split over three pages is one table;
  - total rows — the seventh, and the only one that fails loudly: a TOTAL
    row loaded as data double-counts every aggregate built on it.

Everything here is a pure function over the parse artifact. That is
deliberate and it is the ticket's own instruction: this is the most testable
code in the roadmap and the code where a mistake is most expensive, so the
table tests are the deliverable rather than the decoration.

**No model is called from this package, ever.** A model asked to type a
column is a model that will confidently type the one column it cannot read,
and the failure would be invisible: a plausible number in a plausible column.
Deterministic code that refuses — a column with one unreadable cell becomes
text rather than dropping the cell — is worth more than a clever one that
guesses.
*/

/**
 * ColumnType is what a column holds, decided from every cell in it.
 * There is no "mixed". A column is numeric only when *every* non-empty cell
 * parses; one cell that does not makes the whole column text. The alternative —
 * typing a 95%-numeric column as numeric and nulling the rest — is how a
 * figure with a footnote marker on it disappears from a total, and a figure
 * that disappears is worse than a column that has to be read as strings.
 */
export type ColumnType = string;
export const ColumnText: ColumnType = "text";
export const ColumnInteger: ColumnType = "integer";
export const ColumnDecimal: ColumnType = "decimal";
export const ColumnCurrency: ColumnType = "currency";
export const ColumnPercentage: ColumnType = "percentage";
export const ColumnDate: ColumnType = "date";
/**
 * Column is one typed column of an extracted table.
 */
export interface Column {
  /**
   * Header is what the document called it, with a multi-row header resolved
   * into one string: "Q4 2024 › Actual". The separator is a character no
   * header uses, so a reviewer can see the join and a later reader can undo it.
   */
  header: string;
  /**
   * Name is the identifier the warehouse table gets. Slugified from Header,
   * because a column name reaches a model in `get_schema` and has to be
   * legible as well as safe.
   */
  name: string;
  type: ColumnType;
  /**
   * Multiplier is the header-level scale word, 1 when there is none. Recorded
   * rather than silently folded into the values, because an unrecorded
   * multiplier is unauditable: a reviewer looking at 3,863 in the review grid
   * and 3,863,000,000 in the warehouse has no way to tell whether that was
   * intended.
   */
  multiplier: number /* float64 */;
  /**
   * MultiplierSource is the phrase that produced it — "dalam jutaan Rupiah" —
   * so the review surface can show what it read rather than only what it
   * concluded.
   */
  multiplier_source?: string;
  /**
   * Currency is the symbol or code seen on the cells, when there was one.
   */
  currency?: string;
  /**
   * Precision is how many decimal places the document *printed*. It is the
   * tolerance the arithmetic check compares at — not a display hint.
   */
  precision: number /* int */;
  /**
   * PII is the class T-P12 assigned at publish: "", "identity" or "contact".
   */
  pii?: string;
}
/**
 * Cell is one cell, kept with its raw text whatever its type.
 * The raw string survives typing on purpose. It is what the review surface
 * shows beside the page, it is what a mismatch message quotes, and it is the
 * only way to answer "what did the document actually print here?" after a
 * multiplier has been applied.
 */
export interface Cell {
  raw: string;
  /**
   * Num is the parsed value, multiplier applied, when the column is numeric
   * and this cell is not empty.
   */
  num?: number /* float64 */;
  /**
   * Date is the ISO-8601 rendering when the column typed as a date.
   */
  date?: string;
}
/**
 * Row is one row of data, and where in the document it came from.
 * The provenance is not bookkeeping: T-P6 materializes `source_page` and
 * `source_row` as real columns, so a figure that looks wrong is one query away
 * from the page that produced it. A row that cannot say where it came from is
 * a row nobody can check.
 */
export interface Row {
  cells: Cell[];
  page: number /* int */;
  /**
   * Total is empty for a data row, and says how this row was recognised as a
   * total when it is one: "label" for a row whose first cell says TOTAL,
   * "arithmetic" for one whose numbers turned out to be the sum of the rows
   * above it. The distinction is not cosmetic — T-P5 declines to count the
   * second as evidence, because a row identified *by* adding up cannot then
   * prove that the table adds up.
   */
  total?: string;
  /**
   * Index is the row's position in the candidate grid on that page, header
   * rows included, so it addresses the page rather than the extraction.
   */
  index: number /* int */;
}
/**
 * Table is one extracted table: typed columns, data rows, and the rows this
 * package refused to treat as data.
 */
export interface Table {
  /**
   * Title is the caption found above the grid, when there was one. It is also
   * where a scale word most often hides.
   */
  title: string;
  first_page: number /* int */;
  last_page: number /* int */;
  columns: Column[];
  rows: Row[];
  /**
   * Totals are the rows that state the document's own answer. Flagged and
   * held aside — never silently dropped, because a total row is the evidence
   * T-P5 checks the parse against, and never in Rows, because a TOTAL loaded
   * as data double-counts every aggregate built on it.
   */
  totals: Row[];
  /**
   * Boxes is where the table sat, one rectangle per page it spans.
   */
  boxes?: PageBox[];
  /**
   * Candidate is the parser's index for this grid on its first page. With
   * FirstPage it forms [Table.Key], which is how a re-parse finds the draft a
   * reviewer has been editing instead of creating a second one beside it.
   */
  candidate: number /* int */;
  /**
   * Strategy is the parser's: `lines` when ruling lines defined the grid,
   * `text` when word alignment did. It reaches the reviewer because the
   * second is an inference.
   */
  strategy: string;
  /**
   * Notes are what this package did that a reviewer would not otherwise see —
   * a caption dropped, three pages joined, a column forced to text by one
   * cell. Written for a person, in order.
   */
  notes?: string[];
  /**
   * Verify is T-P5's outcome. Zero value is an unverified table, which is a
   * legal state: most tables state no total to check.
   */
  verify: Verification;
}
/**
 * Options tunes the extraction. The zero value is the shipped behaviour.
 */
export interface Options {
  /**
   * MaxHeaderRows bounds how many leading rows may be merged into one header.
   * Three is enough for "2024 / Q4 / Actual" and small enough that a table
   * whose first data rows are text cannot eat itself.
   */
  MaxHeaderRows: number /* int */;
  /**
   * MinRows is how many data rows a candidate needs to be worth keeping. Two
   * consecutive prose lines look like a two-by-two grid to the text strategy,
   * and the roadmap's own gate produced exactly that.
   */
  MinRows: number /* int */;
}

//////////
// source: verify.go

/**
 * VerifyStatus is what the check concluded about one table.
 */
export type VerifyStatus = string;
/**
 * VerifyUnverified means the document stated no total to check against.
 * It is the common case and it is publishable: most tables are a list of
 * facts, and a list of facts is not wrong for failing to add up.
 */
export const VerifyUnverified: VerifyStatus = "unverified";
/**
 * VerifyVerified means a stated total was re-derived and matched.
 */
export const VerifyVerified: VerifyStatus = "verified";
/**
 * VerifyQuarantined means a stated total was re-derived and did not match.
 * The table is kept — the reviewer needs to see it — and cannot be
 * published through any path.
 */
export const VerifyQuarantined: VerifyStatus = "quarantined";
/**
 * Verification is the outcome, with enough detail for the sentence T-P7 puts on
 * screen: "stated 3.863.405.700, derived 3.860.405.700, difference 3.000.000".
 */
export interface Verification {
  status: VerifyStatus;
  /**
   * Detail names both figures and the gap, per failing column. Empty when
   * nothing failed.
   */
  detail?: string;
  /**
   * Checked is how many column totals were re-derived. Zero with a
   * `verified` status is impossible by construction, and it is the number
   * that says how much the badge is worth: one column checked out of nine is
   * a weaker claim than nine out of nine.
   */
  checked: number /* int */;
}
