// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Entities, from apps/backend/internal/domain.

//////////
// source: action.go

/**
 * InvocationStatus is where an action proposal sits in its lifecycle (T-10).
 * 	proposed ─approve─▶ approved ─execute─▶ executed
 * 	   │                                └──▶ failed
 * 	   ├─reject──▶ rejected
 * 	   └─(24h)───▶ expired
 * Named InvocationStatus, not ActionStatus: ActionStatus already exists on the
 * audit log (agent_action.go) and means how a *tool call* ended. These are
 * different alphabets for different tables, and collapsing them would let a
 * value legal in one row leak into the other.
 */
export type InvocationStatus = string;
export const InvocationProposed: InvocationStatus = "proposed";
export const InvocationApproved: InvocationStatus = "approved";
export const InvocationRejected: InvocationStatus = "rejected";
export const InvocationExecuted: InvocationStatus = "executed";
export const InvocationFailed: InvocationStatus = "failed";
export const InvocationExpired: InvocationStatus = "expired";
/**
 * CompanyAction is one tenant's configuration of one action kind (T-10): whether
 * it is enabled, whether a proposal of it still needs a human decision, the roles
 * that may make that decision, and the sealed configuration the action carries.
 * Nothing can be proposed for a kind that is not enabled here — the agent's
 * write-capable surface is exactly what the admin has switched on, and no wider.
 */
export interface CompanyAction {
  id: string;
  company_id: string;
  action_kind: string;
  enabled: boolean;
  /**
   * RequiresApproval defaults true. False is an explicit admin opt-in that lets
   * a proposal execute immediately — it never becomes the default a company
   * drifts into, and it does not turn off the audit trail.
   */
  requires_approval: boolean;
  /**
   * AllowedRoles are the roles permitted to approve this kind. Empty means any
   * member. Enforced at the approval endpoint (T-11).
   */
  allowed_roles: string[];
  created_by?: string;
  created_at: string;
  updated_at: string;
}
/**
 * ActionInvocation is one proposal moving through the lifecycle above (T-10).
 * ParamsRedacted holds the parameters with credential-shaped values stripped;
 * because an action's real secret lives in CompanyAction.ConfigEncrypted, a
 * well-formed proposal's parameters carry nothing redaction removes, and the
 * executor runs off this field rather than a second unredacted one that would
 * put secrets in the ledger.
 */
export interface ActionInvocation {
  id: string;
  company_id: string;
  thread_id?: string;
  message_id?: string;
  action_kind: string;
  /**
   * ParamsRedacted is json.RawMessage so the pending-approvals endpoint returns
   * the object itself rather than a base64 blob (see AgentAction.ArgsRedacted).
   */
  params_redacted: unknown;
  /**
   * Description is the sentence an approver reads instead of the raw
   * parameters — "Call the registered HTTP endpoint "ops_ticket" with …".
   * Computed on read by ActionService from the action's own Describe, never
   * stored: the row already holds the parameters it is derived from, and a
   * stored copy would be a second truth that a code change could not correct
   * for proposals already written. Empty when the deployment no longer has the
   * kind registered.
   */
  description?: string;
  /**
   * CanDecide is whether *the caller who asked for this row* may approve or
   * reject it — the same question PermittedToDecide answers at decision time,
   * answered early so the card can render the buttons as disabled instead of
   * offering a 403. Computed per request from the kind's allowed_roles, never
   * stored, and never load-bearing: the check that enforces anything is the one
   * in the decide handler, and this field travels to a browser where a user can
   * edit it freely.
   */
  can_decide: boolean;
  idempotency_key: string;
  status: InvocationStatus;
  proposed_at: string;
  decided_at?: string;
  decided_by?: string;
  executed_at?: string;
  result?: unknown;
  error_text?: string;
}

//////////
// source: agent.go

/**
 * Agent is one entry in a company's roster (T-S1).
 * The customer has four jobs and one agent: Marketing, Ops, HR and Finance ask
 * incompatible questions of incompatible data through a single prompt. An
 * Agent is persona + tools + sources — a named, tenant-editable configuration
 * of the one pipeline this product runs.
 * It is **not** an access boundary. Company membership remains the
 * authorization boundary, so any member can open any of their company's
 * agents; the Finance agent physically cannot query the HR source, but nothing
 * stops an employee from opening it and asking what it can reach. Per-agent
 * user grants are a follow-on, and this struct is shaped so adding them later
 * changes no field here.
 * T-S2 is what reads these rows at turn time: the persona is appended to the
 * system prompt, AllowedTools filters the registry the turn is built with, and
 * SourceIDs becomes the scope tools.ResolveSource enforces.
 */
export interface Agent {
  id: string;
  company_id: string;
  name: string;
  description: string;
  /**
   * PersonaPrompt is appended to the shared system prompt, never a
   * replacement for it (bootstrap.SystemPrompt). The shared prompt carries
   * the SQL-dialect rules, the anti-fabrication language and the formatting
   * contract; a customer-authored prompt that could replace it would be a
   * self-service route back to fabricated answers.
   */
  persona_prompt: string;
  /**
   * AllowedTools is empty for "every registered tool". See AllowsTool.
   */
  allowed_tools: string[];
  /**
   * SourceIDs is empty for "every source the company owns". See
   * AllowsSource. Stored in agent_sources rather than inline: these are real
   * foreign keys, and a deleted connection has to leave every agent's
   * allowlist with it.
   */
  source_ids: string[];
  /**
   * MCPServerIDs is the tenant MCP servers this agent may call (T-M2). Unlike
   * SourceIDs, **empty means NONE** — see AllowsMCPServer. Stored in
   * agent_mcp_servers, and a deleted server leaves every agent's binding with
   * it, exactly as a deleted connection leaves SourceIDs.
   */
  mcp_server_ids: string[];
  /**
   * TemplateKey records which gallery card this agent was created from
   * (T-B3), or "" for the blank path and for every agent that predates it.
   * **Analytics only — never read at turn time** (locked decision 4). Nothing
   * in the composed prompt consults it, and editing a template in
   * config/agent_templates.yaml changes no agent that already exists: the
   * text was copied into this row at create time and belongs to the tenant
   * from that moment. The dashboard reads it for one thing only, which is
   * which starter questions to offer on an empty thread.
   */
  template_key: string;
  is_default: boolean;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: agent_action.go

/**
 * ActorKind is the authority a tool call ran under. It answers "who is
 * accountable for this", which is not the same question as "who was in the
 * room": a scheduled report runs with nobody watching, and a T-13 API key
 * belongs to an integration rather than to a person.
 */
export const ActorKindUser = "user";
export const ActorKindSchedule = "schedule";
export const ActorKindWatcher = "watcher"; // T-08
export const ActorKindAPIKey = "api_key"; // T-13
export type ActorKind = typeof ActorKindUser | typeof ActorKindSchedule | typeof ActorKindWatcher | typeof ActorKindAPIKey;
/**
 * ActionStatus is how a tool call ended.
 */
export const ActionStatusOK = "ok";
export const ActionStatusError = "error";
/**
 * ActionStatusBlocked means the call never ran: the turn's budget was
 * spent (T-16), or a guardrail replaced the reply the turn produced.
 */
export const ActionStatusBlocked = "blocked";
/**
 * ActionStatusTruncated means it ran and the result did not fit — the
 * model saw less than the tool retrieved, which changes how a later
 * answer should be read.
 */
export const ActionStatusTruncated = "truncated";
export type ActionStatus = typeof ActionStatusOK | typeof ActionStatusError | typeof ActionStatusBlocked | typeof ActionStatusTruncated;
/**
 * AgentAction is one immutable record of something the agent did.
 * ArgsRedacted keeps the full SQL text — that is the point of the log — and
 * drops anything credential-shaped. ArgsHash is taken over the arguments as
 * the tool received them, before redaction, so identical calls collide even
 * when the stored form does not show why.
 */
export interface AgentAction {
  id: string;
  company_id: string;
  thread_id?: string;
  message_id?: string;
  actor_kind: ActorKind;
  actor_ref?: string;
  channel?: Channel;
  /**
   * AgentID names the roster agent the turn ran as (T-S2). It carries no
   * foreign key and it is never cleared: "which agent ran this query" is a
   * question asked about deleted agents more often than about live ones.
   * Empty for a turn that ran before the roster existed, or under a company
   * that has none.
   */
  agent_id?: string;
  tool_name: string;
  source_id?: string;
  /**
   * MCPServerID names the tenant MCP server a call went to (T-M2), for the
   * rows an MCP tool writes and empty for every other tool. Like AgentID it
   * carries no foreign key and is never cleared: "which server ran this" is
   * asked about deleted servers more often than live ones.
   */
  mcp_server_id?: string;
  /**
   * ArgsRedacted is json.RawMessage rather than []byte so the audit endpoint
   * returns the object itself; encoding/json renders a []byte as base64, and
   * a log whose arguments have to be decoded before they can be read is a
   * log nobody reads.
   */
  args_redacted: unknown;
  args_hash: string;
  result_status: ActionStatus;
  error_text?: string;
  /**
   * RowsReturned is nil for tools that do not return rows at all, which is a
   * different fact from a query that matched zero.
   */
  rows_returned?: number /* int */;
  duration_ms: number /* int */;
  /**
   * RequestID is the `X-Request-Id` of the HTTP call that started the turn
   * (T-A1). Empty for anything that did not start with one — a cron tick, a
   * watcher, a channel webhook — which is most rows.
   */
  request_id?: string;
  created_at: string;
}
/**
 * AgentActionFilter narrows an audit read. Zero values mean "no filter" except
 * for the window, which the caller always supplies.
 */
export interface AgentActionFilter {
  From: string;
  To: string;
  ThreadID: string;
  Tool: string;
  /**
   * RequestID narrows to one HTTP call (T-A1). It is the filter a support
   * conversation actually starts from: the integrator has a request id and
   * nothing else, so "what did that call do" has to be one query.
   */
  RequestID: string;
  Limit: number /* int */;
  Offset: number /* int */;
}

//////////
// source: agent_binding.go

/**
 * AgentChannelBinding routes one channel address to one roster agent (T-S4).
 * The dashboard (T-S3) and `/v1` (T-S5) reach the roster by letting the caller
 * name an agent. Discord, Lark and WhatsApp have nobody to ask — an inbound
 * message carries a user and a room and no place to put a picker — so the
 * binding is what an admin configures instead, and it is on the *address*
 * rather than on the person: a channel is a room configured for a job, and
 * every message that arrives in it is about that job.
 * Absence is the ordinary state and means the company default. This table holds
 * exceptions.
 */
export interface AgentChannelBinding {
  id: string;
  company_id: string;
  agent_id: string;
  /**
   * AgentName rides along on reads so a bindings table does not have to join
   * the roster in the browser. It is not persisted.
   */
  agent_name?: string;
  channel: Channel;
  /**
   * ExternalID is the Discord channel id, the Lark chat id, or the E.164
   * phone number — stored as the provider gives it, except the phone number,
   * which goes through NormalizePhone for the reason stated there.
   */
  external_id: string;
  created_at: string;
}

//////////
// source: allowed_discord_user.go

/**
 * AllowedDiscordUser records which Discord user IDs are authorized to chat
 * with the agent on behalf of a company. A user may be allowed by more than
 * one company, so the primary key is composite.
 */
export interface AllowedDiscordUser {
  company_id: string;
  discord_user_id: string;
  label?: string;
  added_at: string;
}

//////////
// source: allowed_lark_user.go

/**
 * AllowedLarkUser records which Lark open_ids are authorized to chat with
 * the agent on behalf of a company. A user may be allowed by more than one
 * company (through different Lark apps), so the primary key is composite.
 */
export interface AllowedLarkUser {
  company_id: string;
  lark_open_id: string;
  label?: string;
  added_at: string;
}

//////////
// source: allowed_slack_user.go

/**
 * AllowedSlackUser records which Slack user ids are authorized to chat with
 * the agent on behalf of a company. A user may be allowed by more than one
 * company (through different Slack apps), so the primary key is composite.
 */
export interface AllowedSlackUser {
  company_id: string;
  slack_user_id: string;
  label?: string;
  added_at: string;
}

//////////
// source: api_key.go

/**
 * Scope is one capability an API key may carry. The vocabulary is closed and
 * owned here: a key stores strings, but nothing outside this list can ever be
 * written to one, so a typo in a create request is a 400 rather than a scope
 * that silently grants nothing until someone debugs it.
 * Deny by default. A key with no scopes reaches no route, and every scoped
 * route names the scope it needs — there is no "any authenticated key" tier.
 */
/**
 * ScopeReadMetrics — the metric registry (T-06/T-07).
 */
export const ScopeReadMetrics = "read:metrics";
/**
 * ScopeReadThreads — conversation threads and their messages.
 */
export const ScopeReadThreads = "read:threads";
/**
 * ScopeWriteChat — start a turn. The only scope that spends money on its
 * own, which is why it is a write even though the caller is asking a
 * question.
 */
export const ScopeWriteChat = "write:chat";
/**
 * ScopeReadUsage — token and credit reporting.
 */
export const ScopeReadUsage = "read:usage";
/**
 * ScopeReadAudit — the agent action log (T-05).
 */
export const ScopeReadAudit = "read:audit";
/**
 * ScopeWriteActions — execute an action (T-10/T-12).
 */
export const ScopeWriteActions = "write:actions";
/**
 * ScopeWriteReports — ask for a report: a spec to render, or a prompt to
 * run a turn against (T-A2). Separate from write:chat because the two
 * have different costs and a tenant may well want a key that can produce
 * documents and cannot hold a conversation.
 */
export const ScopeWriteReports = "write:reports";
/**
 * ScopeReadData — read the tenant's own warehouse: the source catalog, a
 * table's schema, and a read-only query (T-14). It gates the MCP server's
 * data tools and no `/v1` route: the API answers questions *about* a turn,
 * and this is the surface where somebody else's agent queries directly.
 * Separate from read:metrics on purpose. A metric is a number an admin
 * defined, validated and named; `run_sql` is arbitrary SQL against every
 * table the connection can see, and a key trusted with the first is not
 * thereby trusted with the second — which is the acceptance criterion T-14
 * states in as many words.
 */
export const ScopeReadData = "read:data";
/**
 * ScopeWriteVisualizations — create a Metabase card or dashboard (T-14).
 * The only MCP tool that writes anything, and it writes to Metabase rather
 * than to a tenant's own system, which is why it is not write:actions.
 */
export const ScopeWriteVisualizations = "write:visualizations";
/**
 * ScopeReadDocuments — list generated documents and re-presign their
 * download URLs (T-A2). Read-only over the tenant's own output.
 */
export const ScopeReadDocuments = "read:documents";
export type Scope = typeof ScopeReadMetrics | typeof ScopeReadThreads | typeof ScopeWriteChat | typeof ScopeReadUsage | typeof ScopeReadAudit | typeof ScopeWriteActions | typeof ScopeWriteReports | typeof ScopeReadData | typeof ScopeWriteVisualizations | typeof ScopeReadDocuments;
/**
 * APIKey is a company-scoped machine credential. It authenticates a script,
 * not a person: there is no role on it, only scopes, because "admin" is a
 * statement about a human's authority over a company and an integration has
 * no authority beyond the capabilities it was minted with.
 * The secret half never appears on this struct. KeyPrefix is the public half
 * and the lookup key; KeyHash is what the secret is checked against and is
 * json:"-" so that no handler can leak it by returning the record.
 */
export const APIKeyActive = "active";
export const APIKeyRevoked = "revoked";
export const APIKeyExpired = "expired";
/**
 * Key status values. A revoked key that has also expired reads as revoked:
 * somebody made a decision about it, and that is the more useful fact.
 */
export type APIKey = typeof APIKeyActive | typeof APIKeyRevoked | typeof APIKeyExpired;

//////////
// source: api_report.go

/**
 * APIReportKind is which door created the job.
 */
export type APIReportKind = string;
/**
 * APIReportAgentic — `POST /v1/reports` took a prompt, ran a real turn and
 * billed tokens for it.
 */
export const APIReportAgentic: APIReportKind = "agentic";
/**
 * APIReportRender — `POST /v1/reports/render` took a spec that overran the
 * synchronous window and became a job. The same shape on purpose: an
 * integrator writing a collection path should write it once.
 */
export const APIReportRender: APIReportKind = "render";
/**
 * APIReportStatus is where a job got to.
 */
export type APIReportStatus = string;
export const APIReportQueued: APIReportStatus = "queued";
export const APIReportRunning: APIReportStatus = "running";
export const APIReportCompleted: APIReportStatus = "completed";
export const APIReportFailed: APIReportStatus = "failed";
/**
 * APIReport is one asynchronous report job (T-A2).
 * It exists because `POST /v1/reports` answers 202 and finishes minutes later,
 * so it has to hand back something the caller can name afterwards. A thread id
 * will not do: a thread outlives the turn and accumulates more of them, so
 * "is my report ready?" would have no answer.
 */
export interface APIReport {
  id: string;
  company_id: string;
  api_key_id?: string;
  /**
   * Kind and Format are fixed at creation; everything below Status moves.
   */
  kind: APIReportKind;
  status: APIReportStatus;
  format: DocumentFormat;
  prompt?: string;
  /**
   * ThreadID is empty for a render job — it has no conversation.
   */
  thread_id?: string;
  document_id?: string;
  /**
   * CallbackURL is where the signed `report.completed` body goes. Empty is
   * the ordinary case: most callers poll or stream.
   */
  callback_url?: string;
  /**
   * Error is written for an integrator reading it in their own logs, never a
   * raw Go error — a wrapped chain names our internals and means nothing to
   * the person who has to act on it.
   */
  error?: string;
  request_id?: string;
  created_at: string;
  completed_at?: string;
}

//////////
// source: api_request.go

/**
 * APIRequestSample is one finished `/v1` request, as the middleware observed
 * it. It is the input to the recorder and is never stored in this shape: the
 * counters go to a rollup and only the failures keep their detail.
 * CompanyID and APIKeyID are empty when the request never authenticated. Such a
 * sample still counts on /metrics and is never persisted, because a 401 from an
 * unknown credential belongs to no tenant — attributing it to one would mean
 * guessing, and showing it to all of them would leak another tenant's traffic.
 */
export interface APIRequestSample {
  CompanyID: string;
  APIKeyID: string;
  /**
   * RequestID is the value the caller was handed in `X-Request-Id`. It is the
   * only handle they have when they ask us what happened.
   */
  RequestID: string;
  Method: string;
  /**
   * Route is the gin pattern (`/v1/reports/:id`), not the concrete path. See
   * 032_api_observability.up.sql for why the distinction is load-bearing.
   */
  Route: string;
  Status: number /* int */;
  /**
   * ErrorCode and ErrorType are the envelope's own fields, empty on a 2xx and
   * on any failure that did not go through apierr.
   */
  ErrorCode: string;
  ErrorType: string;
  Latency: unknown /* time.Duration */;
  At: string;
}
/**
 * APIRequestStatRow is one upsertable rollup bucket.
 */
export interface APIRequestStatRow {
  CompanyID: string;
  APIKeyID: string;
  BucketHour: string;
  Route: string;
  Method: string;
  StatusClass: number /* int */;
  Requests: number /* int64 */;
  LatencyMSSum: number /* int64 */;
  LatencyMSMax: number /* int */;
}
/**
 * APIRequestError is one recorded failure, as the dashboard reads it back.
 */
export interface APIRequestError {
  id: string;
  api_key_id: string;
  request_id: string;
  method: string;
  route: string;
  status: number /* int */;
  /**
   * ErrorCode is what an integrator matches on in their own code, so it is
   * the field the tab shows first. Empty means the failure never reached the
   * error envelope — a panic, or a handler writing its own body.
   */
  error_code?: string;
  error_type?: string;
  latency_ms: number /* int */;
  created_at: string;
}
/**
 * APIKeyRequestStats is the per-key summary the dashboard shows beside a key.
 * The window is on the struct rather than implied, because "412 requests" means
 * nothing without it and the tab must not have to remember which window it
 * asked for.
 */
export interface APIKeyRequestStats {
  api_key_id: string;
  window_hours: number /* int */;
  requests: number /* int64 */;
  failed: number /* int64 */;
  /**
   * ErrorRatePct is failed/requests as a percentage, rounded to one decimal.
   * Derived here rather than in the dashboard so the number in the tab and the
   * number in a support conversation are computed once.
   */
  error_rate_pct: number /* float64 */;
  avg_latency_ms: number /* int */;
  max_latency_ms: number /* int */;
}

//////////
// source: branding.go

/**
 * ReportBranding is the tenant's identity on the documents Argentum generates:
 * the PDF a customer forwards to their board, and the deck presented from it.
 * Every field is optional and every field falls back independently. A tenant
 * with a logo and no colour gets their logo and Argentum's red — the renderer
 * resolves per field rather than per object, because "you configured one thing,
 * so we stopped using our defaults for the rest" is how a half-configured
 * document ends up looking broken rather than partly branded.
 * It is stored as one jsonb column on companies (migration 022). The zero value
 * is a valid, fully-defaulted branding, which is what lets a company that has
 * never opened the Reports tab render exactly as it did before this existed.
 */
export interface ReportBranding {
  /**
   * LogoKey is the object-storage key of the tenant's mark, written by the
   * upload endpoint as branding/{company_id}/logo.png. It is a key and not a
   * URL because a URL from object storage expires; the renderer re-reads the
   * object every time it draws a document.
   */
  logo_key?: string;
  /**
   * PrimaryColor is a #RRGGBB accent replacing the brand red on rules,
   * headings and KPI emphasis. It is validated for contrast against white
   * before it is stored — see app.ValidateBrandingColor. Chart series are
   * deliberately *not* recoloured from it; see the note in the branding
   * service.
   */
  primary_color?: string;
  /**
   * FooterText is a legal line carried on every page and every slide, for the
   * tenants whose compliance team requires one.
   */
  footer_text?: string;
  /**
   * LegalName is the entity the document belongs to when it is not the
   * company's display name — "PT Contoh Sejahtera Tbk" on a document from a
   * workspace called "Contoh". It becomes the PDF's Author property, which is
   * what a document-management system files it under.
   */
  legal_name?: string;
  /**
   * Locale is the default document language ("id", "en") when the model does
   * not name one. Without it the locale is derived from the currency, which
   * is right often enough to be a good default and wrong often enough to be
   * worth overriding.
   */
  locale?: string;
  /**
   * ConfidentialityLabel is the default label ("Internal", "Confidential")
   * for documents whose spec does not carry one. Empty means no label, which
   * is a legitimate choice and not an unset one.
   */
  confidentiality_label?: string;
  /**
   * ShowArgentumCredit keeps the "Generated by Argentum" footer line. It
   * defaults to true through the pointer: a tenant who has never configured
   * branding at all gets the credit, and only an explicit false removes it.
   * A plain bool would make "not configured" and "opted out" the same value.
   */
  show_argentum_credit?: boolean;
}

//////////
// source: company.go

/**
 * PIIRedactionMode is a company's policy for the output redaction rules
 * (T-07b). The values match guardrails.PIIMode, which is where they are acted
 * on; this is the storage and validation half, so the domain does not have to
 * import the policy engine to describe a column.
 */
export type PIIRedactionMode = string;
/**
 * PIIRedactionStrict redacts every kind of personal data the rules find.
 */
export const PIIRedactionStrict: PIIRedactionMode = "strict";
/**
 * PIIRedactionContactOK lets emails and phone numbers through, so a tenant
 * can get the customer contact list they asked for. Identity documents and
 * card numbers are still redacted.
 */
export const PIIRedactionContactOK: PIIRedactionMode = "contact_ok";
/**
 * PIIRedactionOff runs no redaction rule at all.
 */
export const PIIRedactionOff: PIIRedactionMode = "off";
/**
 * Company is a tenant of Argentum. Every user, phone number, DB connection,
 * thread, and usage event is owned by exactly one company.
 */
export interface Company {
  id: string;
  name: string;
  slug: string;
  default_currency: string; // ISO 4217, e.g. "IDR", "USD"
  created_at: string;
  /**
   * PIIRedactionMode governs the output redaction rules for this tenant's
   * turns. Empty on a row written before migration 045 and read as strict,
   * which is the column's default.
   */
  pii_redaction_mode: PIIRedactionMode;
}

//////////
// source: company_profile.go

/**
 * CompanyProfile is what business this workspace is, in the tenant's own words
 * (T-B1).
 * The agent already reads every table name through get_schema, and table names
 * describe structure, not meaning. Nothing in `orders`, `stores` and
 * `stock_movements` says a row in `stores` is a shop with a manager and a rent
 * bill, or that a stock-out is the number the operations lead is actually
 * asking about. This row is where that is written down once, for every agent —
 * a company fact belongs to the company, not to five personas that drift five
 * ways.
 * It is facts, never instructions. The persona carries instructions and is
 * kept in a separate block for exactly that reason (locked decision 1): a
 * stale fact is corrected in one place for every agent, a wrong instruction is
 * corrected on the agent that carries it.
 * A company with no row is the ordinary case and produces no block at all —
 * same rule as the roster's empty allowlist, for the same reason.
 */
export interface CompanyProfile {
  company_id: string;
  /**
   * Industry is the one-line label: "grocery retail", "logistics", "SaaS".
   */
  industry: string;
  /**
   * Description is what the business does. The block's substance.
   */
  description: string;
  /**
   * ContextNotes is free-form: markets, seasonality, what "good" looks like.
   * One field rather than six, because we do not yet know which six.
   */
  context_notes: string;
  /**
   * FiscalYearStartMonth is 1-12. It changes what "last quarter" means, which
   * is the single most common way an analytics answer is right about the
   * numbers and wrong about the period.
   */
  fiscal_year_start_month: number /* int */;
  /**
   * Source is provenance: who wrote this. T-B2 infers profiles, and an
   * inferred profile the tenant has never looked at must be distinguishable
   * from their own words — in the dashboard, and to the ticket that fills it
   * in (locked decision 2).
   */
  source: ProfileSource;
  /**
   * InferredAt is when T-B2 last drafted this. Nil for a profile nobody
   * inferred.
   */
  inferred_at?: string;
  /**
   * UpdatedBy is the admin who last saved it, or empty once that user is
   * deleted — the column is ON DELETE SET NULL, because a departed admin
   * must not take the company's profile with them.
   */
  updated_by?: string;
  created_at: string;
  updated_at: string;
}
/**
 * ProfileSource is how a profile came to say what it says.
 */
/**
 * ProfileSourceHuman is a profile the tenant typed.
 */
export const ProfileSourceHuman = "human";
/**
 * ProfileSourceInferred is T-B2's draft, applied but not yet edited.
 */
export const ProfileSourceInferred = "inferred";
/**
 * ProfileSourceInferredEdited is a draft the tenant has since corrected.
 * It is a third value rather than a flip to "human" because "they read our
 * guess and kept most of it" and "they wrote this from scratch" are
 * different facts about the same text.
 */
export const ProfileSourceInferredEdited = "inferred_edited";
export type ProfileSource = typeof ProfileSourceHuman | typeof ProfileSourceInferred | typeof ProfileSourceInferredEdited;
/**
 * CompanyContextMaxTokens caps the rendered block. The profile is
 * tenant-editable text that joins the system prompt on every turn of every
 * agent and every channel: uncapped, it is both a cost multiplier the person
 * typing it never sees a meter for and a way to push the real instructions out
 * of a context window.
 * 600 tokens is roughly a page — long enough to describe a business, short
 * enough that nobody pastes their annual report into it.
 */
export const CompanyContextMaxTokens = 600;

//////////
// source: connection.go

/**
 * DBConnection is a tenant-supplied analytical database connection. The DSN
 * is stored encrypted at rest; only the database type is in plaintext so the
 * agent can dispatch to the right driver.
 */
export interface DBConnection {
  id: string;
  company_id: string;
  db_type: string; // matches one of internal/adapters/db.Supported
  is_default: boolean;
  label?: string;
  /**
   * Description is a short hint about what this database contains, used by
   * the LLM agent when picking which source to query.
   */
  description: string;
  /**
   * DescriptionSource records how Description was populated:
   *   ""       — uninitialised, autogen pending
   *   "auto"   — generated by the ConnectionDescriber LLM
   *   "manual" — set by the user; autogen must not overwrite it
   */
  description_source: string;
  /**
   * MetabaseDatabaseID links this row to /api/database when db_type is
   * postgres; nil until registration succeeds via Metabase REST API.
   */
  metabase_database_id?: number /* int */;
  /**
   * EnableTableEmbedding turns on the embedding-based table picker for
   * this source. When true and embeddings exist, the chat runner injects
   * a top-K relevant-table hint into the user's message so the agent can
   * call get_schema pre-filtered instead of dumping the full catalog.
   */
  enable_table_embedding: boolean;
  /**
   * EmbeddingsIndexedAt records when the table_embeddings rows for this
   * source were last (re)built. Nil means never indexed.
   */
  embeddings_indexed_at?: string;
  created_at: string;
  updated_at: string;
}
export const DescriptionSourceAuto = "auto";
export const DescriptionSourceManual = "manual";
/**
 * Description sources.
 */
export type DescriptionSource = typeof DescriptionSourceAuto | typeof DescriptionSourceManual;

//////////
// source: dashboard.go

/**
 * SavedDashboard is a persisted Metabase dashboard created by the agent.
 */
export interface SavedDashboard {
  id: string;
  company_id: string;
  thread_id: string;
  metabase_dashboard_id: number /* int */;
  name: string;
  public_url: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: discord_credential.go

/**
 * CompanyDiscordCredential holds one tenant's Discord bot configuration.
 * BotTokenEncrypted is AES-256-GCM via crypto.DSNCipher (same key as DSNs).
 * PublicKey is the Ed25519 hex string from the Discord developer portal and
 * is used only by the interactions HTTP webhook to verify request signatures.
 */
export interface CompanyDiscordCredential {
  CompanyID: string;
  ApplicationID: string;
  PublicKey: string;
  BotTokenEncrypted: string /* []byte */;
  GuildID: string;
  Enabled: boolean;
  CreatedAt: string;
  UpdatedAt: string;
}

//////////
// source: document.go

export const DocumentFormatPDF = "pdf";
export const DocumentFormatXLSX = "xlsx";
export const DocumentFormatCSV = "csv";
export const DocumentFormatPPTX = "pptx";
export type DocumentFormat = typeof DocumentFormatPDF | typeof DocumentFormatXLSX | typeof DocumentFormatCSV | typeof DocumentFormatPPTX;
/**
 * DocumentSource is which door produced a document.
 */
/**
 * DocumentSourceAgent — the generate_document tool, inside a turn.
 */
export const DocumentSourceAgent = "agent";
/**
 * DocumentSourceAPI — either `/v1` door (T-A2). It says nothing about
 * whether there was a thread: the agentic door has one and the render door
 * does not, and reading the thread off the source is the mistake the
 * migration's comment exists to prevent.
 */
export const DocumentSourceAPI = "api";
export type DocumentSource = typeof DocumentSourceAgent | typeof DocumentSourceAPI;
/**
 * Document is a persisted artifact produced by the generate_document tool or
 * by a `/v1` report route. Generic-purpose: invoices, agreements, T&Cs,
 * research summaries, exports.
 */
export interface Document {
  id: string;
  company_id: string;
  /**
   * ThreadID is empty for a document `POST /v1/reports/render` produced.
   * That door takes a spec and returns a file: no LLM, no conversation, and
   * so nothing for a thread to be. Every other path still has one.
   */
  thread_id?: string;
  message_id?: string;
  format: DocumentFormat;
  filename: string;
  storage_key: string;
  size_bytes: number /* int64 */;
  source: DocumentSource;
  /**
   * APIKeyID is the credential that paid for it, empty for the agent path.
   * It is what makes per-key usage answerable, which is one of the four
   * layers the sprint's risk register names against a leaked key.
   */
  api_key_id?: string;
  created_at: string;
}
/**
 * DocumentFilter narrows a company-scoped document listing. A zero value
 * lists everything for the tenant, newest first.
 */
export interface DocumentFilter {
  Format: DocumentFormat;
  /**
   * From/To bound created_at. Zero means unbounded on that side.
   */
  From: string;
  To: string;
  /**
   * CursorTime/CursorID are the (created_at, id) of the last row the caller
   * saw. Both empty starts at the newest row. The pair, not the id alone:
   * two documents can share a microsecond, and a keyset predicate needs a
   * total order or it drops rows silently at a page boundary.
   */
  CursorTime: string;
  CursorID: string;
  /**
   * Limit is the page size. The repository normalises a non-positive or
   * oversized value rather than erroring, matching every other constructor
   * in this codebase.
   */
  Limit: number /* int */;
}

//////////
// source: embedding.go

/**
 * TableEmbedding is one row in the table_embeddings store: a single table's
 * doc string and its vector representation, scoped to a source.
 */
export interface TableEmbedding {
  SourceID: string;
  TableName: string;
  DocText: string;
  DocHash: string;
  Model: string;
  Embedding: number /* float32 */[];
}
/**
 * TableHit is the result of a TopK similarity search.
 */
export interface TableHit {
  TableName: string;
  Distance: number /* float32 */;
}

//////////
// source: http_endpoint.go

/**
 * HTTPEndpoint is one target an http_action may call (T-12b).
 * It is the registered half of the http_action feature: an admin sets up a named
 * endpoint here — a method, a URL whose host is fixed and whose path may carry
 * placeholders, the headers that authenticate it, and an optional body template —
 * and the agent proposes a call by *name*, never by URL. Everything that decides
 * where a call goes and how it is authorized was set by a human; the model only
 * fills the declared holes.
 * The credential lives in Header, sealed at rest. A repository returns it
 * encrypted (HeaderEncrypted) to every caller except the turn-time resolver, which
 * decrypts it into Header for the one moment a request is built. HasHeader is the
 * fact a list view is allowed to see — that a header template is set — without the
 * bytes.
 */
export interface HTTPEndpoint {
  id: string;
  company_id: string;
  /**
   * Name is the stable, company-scoped identifier the agent proposes against,
   * e.g. "create_ticket".
   */
  name: string;
  /**
   * Method is the HTTP verb, upper-cased and validated to a known set at
   * registration.
   */
  method: string;
  /**
   * URLTemplate has a literal scheme://host authority and optional
   * {{.placeholders}} in its path and query. The literal authority is what makes
   * the host un-forgeable from turn-time input.
   */
  url_template: string;
  /**
   * HasHeader reports whether a header template is set, derived on read so no
   * second column can disagree with the bytes.
   */
  has_header: boolean;
  /**
   * BodyTemplate is an optional request-body template, filled from the same
   * values as the URL. Empty for a call with no body.
   */
  body_template: string;
  created_by?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: lark_credential.go

/**
 * CompanyLarkCredential holds one tenant's Lark (Feishu) app configuration.
 * AppSecretEncrypted is AES-256-GCM via crypto.DSNCipher (same key as DSNs).
 * VerificationToken authenticates non-encrypted callbacks. EncryptKey (if
 * set) decrypts AES-256-CBC encrypted event payloads and is also part of the
 * X-Lark-Signature input. BotOpenID is the bot's own open_id, used by the
 * inbound dispatcher to detect @mentions of the bot.
 */
export interface CompanyLarkCredential {
  CompanyID: string;
  AppID: string;
  AppSecretEncrypted: string /* []byte */;
  VerificationToken: string;
  EncryptKey: string;
  BotOpenID: string;
  Enabled: boolean;
  CreatedAt: string;
  UpdatedAt: string;
}

//////////
// source: llm_credentials.go

/**
 * LLMTier enumerates per-company LLM profile slots. Missing row for a tier
 * means the resolver falls back to env-based defaults.
 */
export const LLMTierPrimary = "primary";
export const LLMTierLight = "light";
export const LLMTierEmbedding = "embedding";
export type LLMTier = typeof LLMTierPrimary | typeof LLMTierLight | typeof LLMTierEmbedding;
/**
 * CompanyLLMCredential is one tier of a tenant LLM override. Any of
 * Interface, Model, BaseURL, APIKeyEncrypted may be empty/nil; the resolver
 * merges per-field with env defaults.
 */
export interface CompanyLLMCredential {
  ID: string;
  CompanyID: string;
  Tier: LLMTier;
  Interface: string;
  Model: string;
  BaseURL: string;
  APIKeyEncrypted: string /* []byte */;
  CreatedAt: string;
  UpdatedAt: string;
}

//////////
// source: mcp_server.go

/**
 * MCPTransport is how we reach the server. HTTP only, forever: stdio would mean
 * spawning the tenant's process inside our worker, which is arbitrary code
 * execution wearing a config field (locked decision 3).
 */
/**
 * MCPTransportHTTP is the streamable HTTP transport (2025-03-26 spec).
 */
export const MCPTransportHTTP = "http";
/**
 * MCPTransportSSE is the older HTTP+SSE transport, still what most
 * deployed servers speak.
 */
export const MCPTransportSSE = "sse";
export type MCPTransport = typeof MCPTransportHTTP | typeof MCPTransportSSE;
/**
 * MCPServer is one registered server.
 * AuthEncrypted never leaves the backend: it is `json:"-"` for the same reason
 * DBConnection.DSNEncrypted is, and the read routes additionally report only
 * whether a token is set. A credential a read route returns is a credential any
 * admin session leak hands over.
 */
export interface MCPServer {
  id: string;
  company_id: string;
  name: string;
  description: string;
  url: string;
  transport: MCPTransport;
  /**
   * HasAuth is what the dashboard renders instead of the token: "a token is
   * set" is the only fact about it a browser needs, and it is the fact an
   * admin editing the row is actually looking for.
   */
  has_auth: boolean;
  enabled: boolean;
  /**
   * LastProbedAt and ProbeError are the last discovery attempt. A failure is
   * a saved row with a reason, not a rejected save — a server that is down at
   * 4pm is not a configuration error.
   */
  last_probed_at?: string;
  probe_error: string;
  created_at: string;
  updated_at: string;
}
/**
 * MCPServerTool is one discovered tool, and the review an admin gave it.
 * Nothing here is callable until Approved is true. That is the opposite of the
 * agent roster's rule, where an empty allowlist means every tool, and it is
 * deliberate: there the failure is an agent that cannot answer a question, and
 * here it is a write against a system we do not own.
 */
export interface MCPServerTool {
  id: string;
  server_id: string;
  tool_name: string;
  description: string;
  /**
   * InputSchema is the tool's JSON Schema, as the server gave it. Stored raw
   * because it is what T-M2 hands the model, and rewriting it here would mean
   * two descriptions of one tool's arguments.
   */
  input_schema: unknown;
  /**
   * ReadOnly is the admin's classification, not the server's claim. A server
   * that described `delete_everything` as read-only would be believed
   * otherwise, and the tenant's admin is the only party with standing to say
   * what a tool does to their own system.
   */
  read_only: boolean;
  approved: boolean;
  /**
   * ApprovedDigest is MCPToolDigest at the moment of approval. Discovery
   * compares against it: a server that rewrites a tool's description after
   * approval has changed the text that enters the agent's context, and that
   * shows as drift rather than being adopted silently.
   */
  approved_digest: string;
  discovered_at: string;
}

//////////
// source: message.go

/**
 * MessageRole is the role of the sender in a conversation turn.
 */
export const MessageRoleUser = "user";
export const MessageRoleAssistant = "assistant";
export const MessageRoleTool = "tool";
export const MessageRoleSystem = "system";
export type MessageRole = typeof MessageRoleUser | typeof MessageRoleAssistant | typeof MessageRoleTool | typeof MessageRoleSystem;
/**
 * Message is a single turn (user, assistant, or tool) inside a thread.
 */
export interface Message {
  id: string;
  thread_id: string;
  role: MessageRole;
  content: string;
  tool_calls?: { [key: string]: unknown};
  tokens_in?: number /* int */;
  tokens_out?: number /* int */;
  latency_ms?: number /* int64 */;
  metadata?: { [key: string]: unknown};
  created_at: string;
}
/**
 * MessageFilter is the keyset page a `/v1` transcript read asks for (T-A3).
 * There is no channel or role filter: a transcript with the tool turns removed
 * is a transcript that does not explain itself, and a caller that wants only
 * the assistant's words can read `role`.
 */
export interface MessageFilter {
  CursorTime: string;
  CursorID: string;
  Limit: number /* int */;
}

//////////
// source: metric.go

/**
 * MetricGrain is the natural period one metric value covers. It is what a
 * comparison is measured in ("previous period" = one grain back) and what a
 * watcher evaluates on.
 */
export const MetricGrainDay = "day";
export const MetricGrainWeek = "week";
export const MetricGrainMonth = "month";
export const MetricGrainQuarter = "quarter";
export const MetricGrainYear = "year";
export type MetricGrain = typeof MetricGrainDay | typeof MetricGrainWeek | typeof MetricGrainMonth | typeof MetricGrainQuarter | typeof MetricGrainYear;
/**
 * MetricUnit decides how a value reads: whether it is money, a headcount, a
 * rate, or a bare ratio.
 */
export const MetricUnitCurrency = "currency";
export const MetricUnitCount = "count";
export const MetricUnitPercent = "percent";
export const MetricUnitRatio = "ratio";
export type MetricUnit = typeof MetricUnitCurrency | typeof MetricUnitCount | typeof MetricUnitPercent | typeof MetricUnitRatio;
/**
 * MetricDefinition is one named, validated, parameterised number (T-06).
 * It exists so the same question returns the same answer twice: instead of the
 * agent re-deriving SQL for "revenue last month" on every turn, it runs this
 * definition's template through query_metric with the window bound as
 * parameters. v1 is one number, one source, one window — no dimensions, joins,
 * or DSL.
 */
export interface MetricDefinition {
  id: string;
  company_id: string;
  source_id: string;
  key: string;
  label: string;
  /**
   * Description is what the agent reads to decide whether this metric answers
   * the question, so it is specific rather than decorative.
   */
  description: string;
  /**
   * SQLTemplate is a single SELECT that must contain {{from}} and {{to}}. Those
   * tokens are bound as query parameters at run time, never interpolated — the
   * property that keeps a window value from becoming an injection. Stored with
   * the tokens intact; the dialect's placeholder syntax is applied when it runs.
   */
  sql_template: string;
  /**
   * ValueColumn names the column of the single result row that carries the
   * number. Named rather than positional so a template may select more than
   * the value and stay unambiguous.
   */
  value_column: string;
  grain: MetricGrain;
  unit: MetricUnit;
  /**
   * Currency is set when Unit is currency, empty otherwise.
   */
  currency?: string;
  /**
   * HigherIsBetter is whether a rise is good news — revenue up is good, churn
   * up is not. A delta and a watcher both read it to decide which way alarms.
   */
  higher_is_better: boolean;
  enabled: boolean;
  /**
   * CreatedBy is the admin who defined it, or empty. Unreferenced: a metric
   * outlives the user who wrote it.
   */
  created_by?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: phone.go

/**
 * AllowedPhoneNumber records which phone numbers are authorized to chat with
 * Argentum on behalf of a company. Phone numbers are globally unique across
 * all companies so inbound webhook traffic can be routed by `From` alone.
 */
export interface AllowedPhoneNumber {
  company_id: string;
  phone_number: string;
  label?: string;
  added_at: string;
}

//////////
// source: scheduled_task.go

/**
 * ScheduledRunStatus is how one firing of a scheduled task ended.
 * A named type rather than three untyped constants (T-02b): the constants and
 * the `Status` field were declared independently, so nothing stopped a fourth
 * spelling reaching the column — and the generated TypeScript inherited the
 * weakness as a bare `string` while the dashboard's hand-written type had the
 * three-value union right. The union is the truth; this is where it is now
 * written down.
 */
export const ScheduledRunStatusRunning = "running";
export const ScheduledRunStatusSucceeded = "succeeded";
export const ScheduledRunStatusFailed = "failed";
/**
 * Values written to scheduled_task_runs.status.
 */
export type ScheduledRunStatus = typeof ScheduledRunStatusRunning | typeof ScheduledRunStatusSucceeded | typeof ScheduledRunStatusFailed;
/**
 * ScheduledTask is a cron-driven saved prompt. Each fire reuses the same
 * dedicated thread (ThreadID) so the dashboard can render the run history
 * as a normal conversation.
 */
export interface ScheduledTask {
  id: string;
  company_id: string;
  user_id?: string;
  thread_id: string;
  name: string;
  prompt: string;
  cron_expression: string;
  timezone: string;
  enabled: boolean;
  last_run_at?: string;
  next_run_at?: string;
  created_at: string;
  updated_at: string;
}
/**
 * ScheduledTaskRun is one execution of a ScheduledTask. AssistantMsgID
 * is populated once the agent reply has been persisted to the dedicated
 * thread; it stays nil for failed runs that never produced one.
 */
export interface ScheduledTaskRun {
  id: string;
  task_id: string;
  company_id: string;
  status: ScheduledRunStatus;
  assistant_msg_id?: string;
  error_message?: string;
  started_at: string;
  finished_at?: string;
}

//////////
// source: slack_credential.go

/**
 * CompanySlackCredential holds one tenant's Slack app configuration.
 * BotTokenEncrypted is AES-256-GCM via crypto.DSNCipher (same key as DSNs)
 * and holds the xoxb- bot user token used for chat.postMessage.
 * SigningSecret verifies the v0 request signature on every inbound event.
 * BotUserID is the bot's own user id, used to strip the @mention from the
 * text and to ignore the bot's own messages; it is optional because the
 * webhook can fall back to the `authorizations` array Slack sends.
 */
export interface CompanySlackCredential {
  CompanyID: string;
  AppID: string;
  TeamID: string;
  BotTokenEncrypted: string /* []byte */;
  SigningSecret: string;
  BotUserID: string;
  Enabled: boolean;
  CreatedAt: string;
  UpdatedAt: string;
}

//////////
// source: source_profile.go

/**
 * SourceProfile is what one connected database looks like it is for (T-B2).
 * The tenant already told us what their business is; they told us in DDL. A
 * warehouse with `stores`, `skus`, `stock_movements` and `order_items` is a
 * retailer, and asking the person who just connected it to type "we are a
 * retailer" is asking them to do work we can do. This row is that work's
 * output.
 * It is a draft and only a draft. Nothing here reaches a turn: the agent reads
 * CompanyProfile, and a SourceProfile becomes part of one only when a human
 * presses Apply (locked decision 2). An inferred profile that silently became
 * the agent's view of the business would be a fabrication with a UI.
 * Everything in it is derived from names the tenant's DBA chose, which are
 * untrusted input (locked decision 5) — see BusinessInference's prompt framing
 * and the entity validation that drops tables the schema does not have.
 */
export interface SourceProfile {
  connection_id: string;
  company_id: string;
  /**
   * Industry is the one-line label this source suggests: "grocery retail".
   * Per-source because a company's CRM and its warehouse can imply the same
   * industry from different angles, and the fold picks one.
   */
  industry: string;
  /**
   * Summary is one short paragraph: what this database appears to be for.
   */
  summary: string;
  /**
   * Entities are the tables worth naming, with what a row in each means.
   * Every Table here exists in the introspected schema — see
   * keepKnownEntities for why that check is a security control and not
   * tidiness.
   */
  entities: SourceEntity[];
  /**
   * SchemaFingerprint is the hash of the table and column names this was
   * inferred from. Re-running against an unchanged schema must not spend a
   * second LLM call, and this is the whole mechanism for that.
   */
  schema_fingerprint: string;
  /**
   * Model is which LLM wrote it, recorded because a draft that reads badly is
   * a question about a model version six weeks later.
   */
  model: string;
  inferred_at: string;
}
/**
 * SourceEntity is one table and what a row in it means to the business.
 */
export interface SourceEntity {
  table: string;
  means: string;
}
/**
 * DraftMaxEntities is how many table meanings the context-notes field
 * carries. Twelve lines is a screen; a draft nobody reads to the end is a
 * draft nobody can correct, and the profile block has a 600-token cap
 * waiting for it either way.
 */
export const DraftMaxEntities = 12;
/**
 * DraftIndustryMax matches the industry field's own storage limit so an
 * applied draft cannot be rejected by the validation that guards the form.
 */
export const DraftIndustryMax = 120;
/**
 * Draft limits. They bound what the fold puts in front of a tenant, not what
 * the model may return — the service clamps its own output before storing, and
 * these are what a *company* draft is allowed to grow to once several sources
 * have each contributed.
 */
export type Draft = typeof DraftMaxEntities | typeof DraftIndustryMax;

//////////
// source: thread.go

/**
 * Channel is the entry point a conversation came in through.
 */
export const ChannelWhatsApp = "whatsapp";
export const ChannelDashboard = "dashboard";
export const ChannelDiscord = "discord";
export const ChannelLark = "lark";
export const ChannelSlack = "slack";
/**
 * ChannelAPI is a turn started over the public `/v1` API (T-A1). It is
 * the only channel with no outbound provider: the reply is the HTTP
 * response the caller is already holding open, so ChatRunner.completeWith
 * deliberately does nothing for it.
 */
export const ChannelAPI = "api";
export type Channel = typeof ChannelWhatsApp | typeof ChannelDashboard | typeof ChannelDiscord | typeof ChannelLark | typeof ChannelSlack | typeof ChannelAPI;
/**
 * ConversationThread is one logical conversation. Each phone number gets its
 * own thread chain; threads auto-split on long idle gaps + topic shifts.
 * For Lark, each Lark reply-thread maps 1:1 to one ConversationThread row
 * (one thread = one agent memory); LarkThreadKey is the lookup key
 * (thread_id || root_id || message_id, whichever the event surfaces).
 */
export interface ConversationThread {
  id: string;
  company_id: string;
  channel: Channel;
  phone_number?: string; // empty for dashboard/discord/lark threads
  user_id?: string; // empty for WA/discord/lark threads from non-account holders
  discord_user_id?: string; // empty for non-discord threads
  lark_chat_id?: string; // empty for non-lark threads
  lark_thread_key?: string; // empty for non-lark threads
  lark_open_id?: string; // initiating user's open_id; empty for non-lark threads
  /**
   * Slack keys on two things at once, and 049's comment says why: a message
   * inside a thread is found by (SlackChannelID, SlackThreadTS), a top-level
   * mention or DM by (SlackChannelID, SlackUserID). A thread opened by the
   * latter stores the ts its reply will hang under, so the two agree.
   */
  slack_team_id?: string; // empty for non-slack threads
  slack_channel_id?: string; // empty for non-slack threads
  slack_thread_ts?: string; // empty for non-slack threads
  slack_user_id?: string; // initiating user's id; empty for non-slack threads
  /**
   * APIUserRef is the tenant's own identifier for whoever the API call was
   * made on behalf of (T-A1). It is opaque to us by design: an API key
   * belongs to a company, so the only identity available is the one the
   * caller supplies. Empty for non-api threads.
   */
  api_user_ref?: string;
  /**
   * AgentID is the roster agent this conversation runs as (T-S2). Empty
   * means the company default, which is what every thread predating the
   * roster resolves to and what a thread whose agent was deleted falls back
   * to — the column is ON DELETE SET NULL precisely so that a tidied roster
   * cannot strand a conversation.
   */
  agent_id?: string;
  title: string;
  summary?: string;
  last_message_at: string;
  is_archived: boolean;
  created_at: string;
}
/**
 * ThreadFilter narrows a keyset-paginated thread listing (T-A3).
 * Channel is a filter rather than an assumption because the table holds every
 * channel's conversations in one place. `/v1` always sets it to ChannelAPI: a
 * machine credential listing the threads of named people who have dashboard
 * sessions is a leaked key reading the staff's chat history, and the tenant's
 * own audit surface for those is the dashboard, which is role-gated.
 * APIUserRef narrows further, to one end user of the tenant's own product. It
 * is what makes "neither user_ref can read the other's thread" enforceable by
 * us rather than by the integrator remembering to filter.
 */
export interface ThreadFilter {
  Channel: Channel;
  APIUserRef: string;
  CursorTime: string;
  CursorID: string;
  Limit: number /* int */;
}

//////////
// source: usage.go

/**
 * UsageEventType identifies what kind of work a usage event represents.
 */
export type UsageEventType = string;
export const UsageEventLLMCall: UsageEventType = "llm_call";
export const UsageEventSQLQuery: UsageEventType = "sql_query";
export const UsageEventMetabaseCard: UsageEventType = "metabase_card";
export const UsageEventMetabaseDashboard: UsageEventType = "metabase_dashboard";
export const UsageEventTopicClassify: UsageEventType = "topic_classify";
export const UsageEventDocumentGenerated: UsageEventType = "document_generated";
/**
 * UsageEventMCPCall is one call to a tenant's own MCP server (T-M2). It is
 * its own type rather than folded into sql_query because the work happens on
 * somebody else's machine: the cost we carry is the round trip and the
 * context the result occupies, not a query against a source we hold.
 */
export const UsageEventMCPCall: UsageEventType = "mcp_call";
/**
 * UsageEvent is a single billable / observable action taken on behalf of a
 * company. Persisted for usage display today; will back per-call billing in
 * V2.
 */
export interface UsageEvent {
  id: string;
  company_id: string;
  thread_id?: string;
  message_id?: string;
  /**
   * AgentID attributes the spend to a roster agent (T-S2). No foreign key,
   * same reasoning as agent_actions: a deleted agent's costs stay on the
   * month they were incurred in. Empty when the turn ran unscoped.
   */
  agent_id?: string;
  event_type: UsageEventType;
  model?: string;
  tokens_in?: number /* int */;
  tokens_out?: number /* int */;
  cache_create_tokens_in?: number /* int */;
  cache_read_tokens_in?: number /* int */;
  cost_micro_usd: number /* int64 */;
  metadata?: { [key: string]: unknown};
  created_at: string;
}
/**
 * UsageSummary is an aggregate view returned to the dashboard.
 */
export interface UsageSummary {
  from: string;
  to: string;
  total_cost_usd: number /* float64 */;
  total_tokens_in: number /* int64 */;
  total_tokens_out: number /* int64 */;
  event_counts: { [key: UsageEventType]: number /* int64 */};
  cost_by_event_type_usd: { [key: UsageEventType]: number /* float64 */};
  cost_by_model_usd?: { [key: string]: number /* float64 */};
  tokens_in_by_model?: { [key: string]: number /* int64 */};
  tokens_out_by_model?: { [key: string]: number /* int64 */};
}
/**
 * ThreadUsageRow is one row in the per-thread usage listing.
 */
export interface ThreadUsageRow {
  thread_id: string;
  channel: Channel;
  title?: string;
  last_message_at: string;
  event_count: number /* int64 */;
  tokens_in: number /* int64 */;
  tokens_out: number /* int64 */;
  cache_create_tokens_in: number /* int64 */;
  cache_read_tokens_in: number /* int64 */;
  cost_usd: number /* float64 */;
}
/**
 * ChannelUsageRow rolls cost up by entry channel.
 */
export interface ChannelUsageRow {
  channel: Channel;
  thread_count: number /* int64 */;
  event_count: number /* int64 */;
  tokens_in: number /* int64 */;
  tokens_out: number /* int64 */;
  cost_usd: number /* float64 */;
}
/**
 * UserUsageRow rolls cost up by end-user identity. UserKey is the first
 * non-empty of user_id / phone_number / discord_user_id / lark_open_id;
 * UserKeyKind labels which column produced it.
 */
export interface UserUsageRow {
  channel: Channel;
  user_key: string;
  user_key_kind: string;
  thread_count: number /* int64 */;
  event_count: number /* int64 */;
  tokens_in: number /* int64 */;
  tokens_out: number /* int64 */;
  cost_usd: number /* float64 */;
}
/**
 * CompanyCredits tracks the soft balance for a company.
 */
export interface CompanyCredits {
  company_id: string;
  balance_micro_usd: number /* int64 */;
  monthly_grant_micro_usd: number /* int64 */;
  updated_at: string;
}

//////////
// source: user.go

/**
 * Role is the access role of a user within their company.
 */
export const RoleAdmin = "admin";
export const RoleMember = "member";
export type Role = typeof RoleAdmin | typeof RoleMember;
/**
 * User is a dashboard account, always scoped to exactly one company.
 */
export interface User {
  id: string;
  company_id: string;
  email: string;
  role: Role;
  created_at: string;
  /**
   * ActivatedAt is nil for a user created by an invite that nobody has
   * accepted yet. DeactivatedAt is non-nil once an admin removes them. Both
   * are checked on every login and every refresh.
   */
  activated_at?: string;
  deactivated_at?: string;
}

//////////
// source: user_invite.go

/**
 * UserInvite is a single-use grant that lets one email address activate a
 * pending user in one company. The plaintext token is shown to the inviting
 * admin exactly once and never stored: TokenHash is what persists.
 */
export interface UserInvite {
  id: string;
  company_id: string;
  email: string;
  role: Role;
  expires_at: string;
  accepted_at?: string;
  invited_by?: string;
  created_at: string;
}

//////////
// source: watcher.go

/**
 * WatcherGrain is the period one watcher evaluation covers (T-08). A subset of
 * MetricGrain: a watcher runs on a cron, and day/week/month are the cadences a
 * human reads a business on. Quarter and year are metric grains for a report,
 * not alert windows.
 */
export const WatcherGrainDay = "day";
export const WatcherGrainWeek = "week";
export const WatcherGrainMonth = "month";
export type WatcherGrain = typeof WatcherGrainDay | typeof WatcherGrainWeek | typeof WatcherGrainMonth;
/**
 * WatcherComparator is the condition a watcher breaches on (T-08).
 * The threshold comparators read the metric's value directly; the pct_change
 * comparators read the delta against a comparison window and so require
 * CompareTo; no_data breaches when the metric returns no usable row at all,
 * which is how a watcher catches a stalled pipeline rather than a bad number.
 */
export const WatcherComparatorGT = "gt";
export const WatcherComparatorLT = "lt";
export const WatcherComparatorPctChangeGT = "pct_change_gt";
export const WatcherComparatorPctChangeLT = "pct_change_lt";
export const WatcherComparatorNoData = "no_data";
export type WatcherComparator = typeof WatcherComparatorGT | typeof WatcherComparatorLT | typeof WatcherComparatorPctChangeGT | typeof WatcherComparatorPctChangeLT | typeof WatcherComparatorNoData;
/**
 * WatcherChannel is one delivery destination for a watcher's fire.
 * Ref means whatever the channel keys delivery on: a WhatsApp phone number, a
 * Discord channel id, a Lark chat id. The dashboard channel has no ref — the
 * watcher's dedicated thread is where it lands — so Ref is empty there.
 */
export interface WatcherChannel {
  channel: Channel;
  ref?: string;
}
/**
 * WatcherDelivery is one channel's outcome for one fire, stored in
 * watcher_events.delivery_status.
 */
export interface WatcherDelivery {
  channel: Channel;
  ref?: string;
  /**
   * Status is "delivered", "failed", or "skipped" (a channel with no provider
   * wired in this deployment).
   */
  status: string;
  error?: string;
}
/**
 * Watcher is a metric-condition trigger (T-08): evaluate MetricID on a cron, and
 * when Comparator/Threshold breaches, fire an agent turn into Channels.
 */
export interface Watcher {
  id: string;
  company_id: string;
  metric_id: string;
  /**
   * ThreadID is the dedicated thread each fire runs in, reused across fires so
   * the dashboard shows one conversation per watcher.
   */
  thread_id: string;
  name: string;
  window_grain: WatcherGrain;
  comparator: WatcherComparator;
  threshold: number /* float64 */;
  compare_to?: string;
  cron_expression: string;
  timezone: string;
  channels: WatcherChannel[];
  cooldown_minutes: number /* int */;
  enabled: boolean;
  last_fired_at?: string;
  last_dry_run_at?: string;
  created_by?: string;
  created_at: string;
  updated_at: string;
}
/**
 * WatcherEvent is one evaluation of a watcher, breached or not (T-08).
 */
export interface WatcherEvent {
  id: string;
  watcher_id: string;
  company_id: string;
  fired_at: string;
  /**
   * MetricValue/ComparisonValue/DeltaPct are nil when the evaluation had no
   * number to record: a no_data breach, or a threshold breach with no
   * comparison window.
   */
  metric_value?: number /* float64 */;
  comparison_value?: number /* float64 */;
  delta_pct?: number /* float64 */;
  breached: boolean;
  /**
   * SuppressedReason is "cooldown" when a real breach did not fire; empty
   * otherwise.
   */
  suppressed_reason?: string;
  thread_id?: string;
  message_id?: string;
  delivery_status?: WatcherDelivery[];
}

//////////
// source: webhook_delivery.go

/**
 * WebhookDeliveryStatus is where one outbound callback got to.
 */
export type WebhookDeliveryStatus = string;
export const WebhookPending: WebhookDeliveryStatus = "pending";
export const WebhookDelivered: WebhookDeliveryStatus = "delivered";
/**
 * WebhookFailed is set once the retry budget is spent, not on the first
 * refusal. A receiver that was redeploying and answered 502 twice has not
 * failed; a row that said so would make the log useless for the question
 * it exists to answer.
 */
export const WebhookFailed: WebhookDeliveryStatus = "failed";
/**
 * WebhookDelivery is one attempt to hand a tenant's server an event, and the
 * record of how it went (T-A2).
 * The record is half the feature. "We never got the callback" is otherwise an
 * unanswerable support ticket: without a row there is nothing to say whether
 * we sent it, what we sent, or what their server answered.
 */
export interface WebhookDelivery {
  id: string;
  company_id: string;
  event: string;
  url: string;
  status: WebhookDeliveryStatus;
  attempts: number /* int */;
  /**
   * LastStatus is the receiver's HTTP status, or 0 when the request never
   * got one — DNS, TLS, a timeout. That distinction is the first thing to
   * look at and it is lost if both are recorded as a failure.
   */
  last_status: number /* int */;
  last_error?: string;
  created_at: string;
  delivered_at?: string;
  /**
   * SubscriptionID is the standing subscription this delivery came from
   * (T-15), and empty for a `report.completed` callback, which belongs to the
   * one request that named its URL. It is what lets the worker count a
   * terminal failure against the subscription that caused it rather than
   * guessing by URL — two subscriptions may legitimately share one.
   */
  subscription_id?: string;
}

//////////
// source: webhook_subscription.go

/**
 * WebhookWatcherBreached fires when a watcher's condition is met and the
 * briefing turn has been enqueued (T-08).
 */
export const WebhookWatcherBreached = "watcher.breached";
/**
 * WebhookActionExecuted fires when an approved action ran — including one
 * that ran and failed, because "we tried and it did not work" is the event
 * an integration most needs (T-10).
 */
export const WebhookActionExecuted = "action.executed";
/**
 * WebhookScheduledTaskCompleted fires when a scheduled task's turn ends.
 */
export const WebhookScheduledTaskCompleted = "scheduled_task.completed";
/**
 * Webhook event names (T-15). The vocabulary is closed and lives here, because
 * a subscription to an event nobody publishes is a tenant waiting for a
 * delivery that will never come — and the failure is silent at every layer
 * below this one.
 * Report callbacks are deliberately absent. `POST /v1/reports` takes a
 * `callback_url` per request (T-A2): the caller is waiting on that one report
 * and named the URL in the same breath, which is a different thing from a
 * standing subscription to what a workspace does.
 */
export type Webhook = typeof WebhookWatcherBreached | typeof WebhookActionExecuted | typeof WebhookScheduledTaskCompleted;
/**
 * WebhookAutoDisableAfter is how many consecutive failed deliveries disable a
 * subscription (T-15).
 * Twenty rather than three: a tenant's server being down for an hour is
 * ordinary, and disabling on the first blip would make this feature something
 * people stop trusting. Twenty consecutive terminal failures — each of which is
 * already five delivery attempts with backoff — is a server that is not coming
 * back without someone looking at it.
 */
export const WebhookAutoDisableAfter = 20;
/**
 * WebhookSubscription is one tenant's standing request to be told when
 * something happens (T-15).
 * The signing secret is not here: it is the company's, on `companies.
 * webhook_secret`, minted on first use and shared by every callback we send
 * them — a receiver verifying two subscriptions with one secret is the shape
 * every webhook integration expects, and rotating per subscription would mean a
 * tenant holding a table of secrets.
 */
export interface WebhookSubscription {
  id: string;
  company_id: string;
  url: string;
  /**
   * Events is what this subscription wants. Empty is not "everything" — it is
   * a subscription that matches nothing, and the service refuses to store one.
   * The opposite rule to an agent's tool allowlist, and deliberately: there,
   * an empty list widens what an agent may do inside Argentum; here it would
   * widen what leaves it.
   */
  events: string[];
  enabled: boolean;
  /**
   * ConsecutiveFailures counts terminal delivery failures since the last
   * success. Reset to zero by any delivery that lands.
   */
  consecutive_failures: number /* int */;
  /**
   * DisabledReason is set when this system disabled the subscription rather
   * than the tenant. Empty for one an admin switched off, so the settings
   * screen can tell "you turned this off" from "we did, and here is why".
   */
  disabled_reason?: string;
  last_success_at?: string;
  last_failure_at?: string;
  created_at: string;
  updated_at: string;
}
