// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// WebSocket frames, the credit position and the skills surface's
// response shapes, from apps/backend/internal/app.

//////////
// source: budget_state.go

/**
 * BudgetVerdict is what a budget check concluded. The three values are the
 * whole vocabulary: everything downstream branches on these, not on the
 * balance.
 */
export type BudgetVerdict = string;
/**
 * BudgetOK — the turn may run.
 */
export const BudgetOK: BudgetVerdict = "ok";
/**
 * BudgetWarning — the turn may run, and the tenant should be told they
 * are close to the end of their credit.
 */
export const BudgetWarning: BudgetVerdict = "warning";
/**
 * BudgetExhausted — the turn is refused before any money is spent.
 */
export const BudgetExhausted: BudgetVerdict = "exhausted";
/**
 * BudgetState is one company's spend position at the moment it was checked.
 * It carries the balance and grant as well as the verdict because the
 * dashboard's warning banner has to say how much is left, and re-reading the
 * balance to render it would defeat the cache this check exists behind.
 */
export interface BudgetState {
  verdict: BudgetVerdict;
  balance_micro_usd: number /* int64 */;
  grant_micro_usd: number /* int64 */;
  /**
   * RemainingPct is the balance as a percentage of the grant, 0–100. Zero
   * when there is no grant to measure against.
   */
  remaining_pct: number /* int */;
  /**
   * BYOLLM marks a tenant running on their own LLM credentials. They pay
   * their provider directly, so no balance was consulted and none applies.
   */
  byo_llm: boolean;
  /**
   * Enforced distinguishes "the balance is zero" from "no balance was
   * consulted" (T-A1). Without it `GET /v1/me` would report a $0.00 credit
   * balance on a deployment with enforcement switched off, which reads as
   * "you are out of credit" — the opposite of the truth. It is false on the
   * fail-open paths too, and that is accurate rather than convenient:
   * nothing was enforced for that call either.
   */
  enforced: boolean;
}
/**
 * CreditsExhaustedMessage is the single refusal every channel sends. It is
 * one string rather than one per channel because a WhatsApp user and a
 * dashboard user hitting the same wall should be told the same thing, and
 * because the alternative is four wordings that drift. It names the fix and
 * avoids the word "error": nothing has gone wrong.
 */
export const CreditsExhaustedMessage = "This workspace has used all of its Argentum credits, " + "so I can't run that right now. Ask an admin to top up the balance — " + "current usage is on the Usage page in the dashboard.";

//////////
// source: event_bus.go

/**
 * OutboundEvent is a final assistant message destined for a channel the
 * worker process can't deliver directly (e.g. Discord, where each tenant
 * has its own gateway session held by cmd/discord).
 */
export interface OutboundEvent {
  channel: string; // domain.Channel string ("discord")
  company_id: string;
  channel_ref: string; // discord_channel_id
  user_ref?: string;
  content: string;
}
/**
 * ToolCallEvent carries live tool-execution metadata for the dashboard.
 */
export interface ToolCallEvent {
  name: string;
  arguments?: { [key: string]: unknown};
  result?: { [key: string]: unknown};
}
/**
 * ChatEvent is one streaming update for a chat run. The dashboard renders
 * these directly. WhatsApp delivery is handled by the worker — no fan-out
 * indirection required anymore.
 */
export interface ChatEvent {
  job_id: string;
  thread_id: string;
  type: string; // state | started | delta | thinking | tool_call | tool_result | final | error | render_progress
  content?: string;
  thinking_step?: string;
  tool_call?: ToolCallEvent;
  error?: string;
  /**
   * Live is set on — and only on — a `state` event: the turn already in
   * flight when this socket opened. Every other event describes something
   * that just happened; this one describes what has happened so far.
   */
  live?: LiveTurn;
  /**
   * Progress is 0..1 on a `render_progress` event and unset on every other
   * type (T-V3). A four-minute video needs a number on the screen, and the
   * dashboard and `/v1` both already read this struct — a second event
   * pipeline for one float is how two vocabularies start.
   */
  progress?: number /* float64 */;
  metadata?: { [key: string]: unknown};
  timestamp: string;
}
/**
 * LiveTurn is everything a turn still running has produced so far, as the
 * first frame of a socket that opened in the middle of it (T-U12).
 * A WebSocket carries what happens *next*, which is enough only for a reader
 * who was watching from the start. Leaving one conversation for another closes
 * its socket, and the one that reopens on the way back used to say nothing at
 * all until the agent's next token — so a turn thinking through a slow tool
 * looked, for as long as that took, like a thread with no answer coming. This
 * is the state that gap needed: the same three signals the streaming bubble
 * already renders — that work is happening, since when, and what it is doing.
 * The event stream stays the source of truth. This is a catch-up frame written
 * alongside every publish and dropped the moment the turn ends, never a second
 * place a turn's result is stored.
 */
export interface LiveTurn {
  job_id: string;
  started_at: string;
  /**
   * LastEventAt is the timestamp of the newest event folded in here. It is
   * how the client recognises the one event a reconnect can see twice: the
   * socket subscribes before this snapshot is read, so anything published in
   * between arrives on the wire *and* is already counted here.
   */
  last_event_at: string;
  content?: string;
  thinking_steps?: string[];
  tool_calls?: ToolCallEvent[];
  iteration?: number /* int */;
  max_iterations?: number /* int */;
}
/**
 * EventState is the catch-up frame described on LiveTurn, sent once per
 * connection and only when a turn is actually running.
 */
export const EventState = "state";
/**
 * EventRenderProgress is emitted while a video renders. It is capped at one a
 * second by the render client's own poll interval, and it never carries 1.0:
 * completion is `final` for a turn and the terminal `report` event for a job,
 * both of which arrive when the file exists rather than when the frames stop.
 */
export const EventRenderProgress = "render_progress";

//////////
// source: skill_wire.go

/**
 * SkillPreview is what an author is shown while typing: the two strings the
 * model will see, and the counts that decide whether the save is refused.
 * **It is rendered by the server rather than by the form**, and that is the
 * whole point of the endpoint. A dashboard that assembled `- name — trigger`
 * itself, or drew its own frame markers, would be a second implementation of
 * the two things this feature is — and the moment it drifted, the preview would
 * be reassuring an author about bytes nobody sends.
 */
export interface SkillPreview {
  /**
   * IndexLine is the line that rides every turn's system prompt.
   */
  index_line: string;
  /**
   * FramedBody is what `load_skill` returns, markers included. It is
   * `skill.Frame`'s output, so an author who pasted a fence marker into their
   * procedure sees it neutralised here rather than discovering it in a turn.
   */
  framed_body: string;
  /**
   * The counts, in runes, because the caps are in runes: a rule that let an
   * English procedure be 8,000 characters and an Indonesian one 5,300 would
   * be a cap on the alphabet.
   */
  name_chars: number /* int */;
  when_to_use_chars: number /* int */;
  body_chars: number /* int */;
  index_line_chars: number /* int */;
  /**
   * Refusal is what Validate would say if this were saved now, or empty.
   * Served so the form can show the sentence the API would answer with
   * rather than inventing its own wording for the same rule.
   */
  refusal?: string;
}
/**
 * SkillIndexCost is what this workspace's procedures cost every turn.
 * **The bound is invisible until somebody looks at the index**, which is the
 * failure T-K9's own negative case measures from the other side: a tenant whose
 * twenty-first procedure is never offered has no way to find that out from the
 * list screen. Dropped names are the answer.
 */
export interface SkillIndexCost {
  /**
   * Chars and Lines are what the composed block actually costs, header
   * included — the header is not free and it is two-thirds of the cost of a
   * workspace with one skill.
   */
  chars: number /* int */;
  lines: number /* int */;
  max_chars: number /* int */;
  max_lines: number /* int */;
  /**
   * Dropped names the procedures that did not fit, in the order they were
   * lost. Non-empty means some of this workspace's own procedures are not
   * offered to any agent on any turn.
   */
  dropped: string[];
}
/**
 * SkillDraft is what the button returns: three fields and the provenance to
 * display beside them.
 */
export interface SkillDraft {
  name: string;
  when_to_use: string;
  body: string;
  /**
   * ThreadID is what it was drafted from, so the form can say so. A tenant
   * about to save a procedure should be able to see which conversation put
   * those words on the screen.
   */
  thread_id: string;
  /**
   * Messages and ToolCalls are how much the draft actually saw. A draft from
   * a two-message thread with no tool calls is a draft from almost nothing,
   * and the person deciding whether to trust it should be told.
   */
  messages: number /* int */;
  tool_calls: number /* int */;
}
