// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// WebSocket frames and the credit position, from apps/backend/internal/app.

//////////
// source: budget_state.go

/**
 * BudgetVerdict is what a budget check concluded. The three values are the
 * whole vocabulary: everything downstream branches on these, not on the
 * balance.
 */
export type BudgetVerdict = string;
/**
 * BudgetOK — the turn may run.
 */
export const BudgetOK: BudgetVerdict = "ok";
/**
 * BudgetWarning — the turn may run, and the tenant should be told they
 * are close to the end of their credit.
 */
export const BudgetWarning: BudgetVerdict = "warning";
/**
 * BudgetExhausted — the turn is refused before any money is spent.
 */
export const BudgetExhausted: BudgetVerdict = "exhausted";
/**
 * BudgetState is one company's spend position at the moment it was checked.
 * It carries the balance and grant as well as the verdict because the
 * dashboard's warning banner has to say how much is left, and re-reading the
 * balance to render it would defeat the cache this check exists behind.
 */
export interface BudgetState {
  verdict: BudgetVerdict;
  balance_micro_usd: number /* int64 */;
  grant_micro_usd: number /* int64 */;
  /**
   * RemainingPct is the balance as a percentage of the grant, 0–100. Zero
   * when there is no grant to measure against.
   */
  remaining_pct: number /* int */;
  /**
   * BYOLLM marks a tenant running on their own LLM credentials. They pay
   * their provider directly, so no balance was consulted and none applies.
   */
  byo_llm: boolean;
  /**
   * Enforced distinguishes "the balance is zero" from "no balance was
   * consulted" (T-A1). Without it `GET /v1/me` would report a $0.00 credit
   * balance on a deployment with enforcement switched off, which reads as
   * "you are out of credit" — the opposite of the truth. It is false on the
   * fail-open paths too, and that is accurate rather than convenient:
   * nothing was enforced for that call either.
   */
  enforced: boolean;
}
/**
 * CreditsExhaustedMessage is the single refusal every channel sends. It is
 * one string rather than one per channel because a WhatsApp user and a
 * dashboard user hitting the same wall should be told the same thing, and
 * because the alternative is four wordings that drift. It names the fix and
 * avoids the word "error": nothing has gone wrong.
 */
export const CreditsExhaustedMessage = "This workspace has used all of its Argentum credits, " + "so I can't run that right now. Ask an admin to top up the balance — " + "current usage is on the Usage page in the dashboard.";

//////////
// source: event_bus.go

/**
 * OutboundEvent is a final assistant message destined for a channel the
 * worker process can't deliver directly (e.g. Discord, where each tenant
 * has its own gateway session held by cmd/discord).
 */
export interface OutboundEvent {
  channel: string; // domain.Channel string ("discord")
  company_id: string;
  channel_ref: string; // discord_channel_id
  user_ref?: string;
  content: string;
}
/**
 * ToolCallEvent carries live tool-execution metadata for the dashboard.
 */
export interface ToolCallEvent {
  name: string;
  arguments?: { [key: string]: unknown};
  result?: { [key: string]: unknown};
}
/**
 * ChatEvent is one streaming update for a chat run. The dashboard renders
 * these directly. WhatsApp delivery is handled by the worker — no fan-out
 * indirection required anymore.
 */
export interface ChatEvent {
  job_id: string;
  thread_id: string;
  type: string; // started | delta | thinking | tool_call | tool_result | final | error | render_progress
  content?: string;
  thinking_step?: string;
  tool_call?: ToolCallEvent;
  error?: string;
  /**
   * Progress is 0..1 on a `render_progress` event and unset on every other
   * type (T-V3). A four-minute video needs a number on the screen, and the
   * dashboard and `/v1` both already read this struct — a second event
   * pipeline for one float is how two vocabularies start.
   */
  progress?: number /* float64 */;
  metadata?: { [key: string]: unknown};
  timestamp: string;
}
/**
 * EventRenderProgress is emitted while a video renders. It is capped at one a
 * second by the render client's own poll interval, and it never carries 1.0:
 * completion is `final` for a turn and the terminal `report` event for a job,
 * both of which arrive when the file exists rather than when the frames stop.
 */
export const EventRenderProgress = "render_progress";
