/* eslint-disable */
// Code generated by packages/api-types. DO NOT EDIT.
//
// The Go structs the dashboard reads off `/api`. Regenerate with `make types`.
//
// Inbound webhook envelopes (apps/backend/pkg/models) are deliberately absent:
// no browser ever receives one, and `models.Message` would collide with
// `domain.Message`. Import them from "@argentum/api-types/webhooks".
//
// The video plan (internal/report/videoplan) is absent for the same reason and
// a sharper one: its `Brand`, `Table` and `Metrics` are names a dashboard
// namespace should not be handed. Import it from
// "@argentum/api-types/videoplan".
//
// The document extraction types (internal/doctable, internal/docparse) are
// absent for exactly that reason: `Table`, `Column`, `Row`, `Cell` and
// `Page` are the five most collision-prone names in a dashboard. Import them
// from "@argentum/api-types/doctable" and "@argentum/api-types/docparse".

export * from "./domain.js";
export * from "./events.js";
export * from "./api.js";
