/* eslint-disable */
// Code generated by packages/api-types. DO NOT EDIT.
//
// The Go structs the dashboard reads off `/api`. Regenerate with `make types`.
//
// Inbound webhook envelopes (apps/backend/pkg/models) are deliberately absent:
// no browser ever receives one, and `models.Message` would collide with
// `domain.Message`. Import them from "@argentum/api-types/webhooks".

export * from "./domain.js";
export * from "./events.js";
export * from "./api.js";
