// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// The video plan, from apps/backend/internal/report/videoplan/plan.go.
// Every string in it is final: nothing on this side formats a number,
// picks a word, or decides how long a scene is on screen.

//////////
// source: plan.go
/*
Package videoplan projects a report spec onto a finished video.

**It renders nothing.** What it produces is a Plan: a list of scenes in which
every string is final, every line is already broken, every duration is already
counted in frames, and every image is already a data URI. The renderer on the
other side (apps/render, T-V2) draws it and decides nothing.

That division is T-V1's locked decision 2, and it is the whole reason this
package exists rather than a JSON encoder somewhere in the handler. The deck
and the PDF agree about what "Prepared for" is in Indonesian, how many
decimals a column takes and how wide it is, because neither of them decides —
internal/report/labels, format and layout do. A third renderer written in
TypeScript, in another process, cannot reach any of that. So either the
decisions travel with the data, or the one format a customer *watches* is the
one that says `Rp 3,863,405,700`.

Two consequences worth stating because they look like over-engineering:

  - **Text arrives pre-wrapped.** Scenes carry lines, not paragraphs. The
    browser is asked to draw strings at fixed positions, never to lay them
    out. A line that fits here fits there because the same font metrics
    decided both — see internal/report/canvas, where the video frame and the
    PowerPoint slide are shown to be the same surface at 2 px per point.
  - **Durations are computed from the text.** The model chooses content; it
    does not choose seconds. spec.Chart.HeightMM's comment makes the general
    argument — a model asked for a number in millimetres picks one that makes
    the aspect ratio wrong — and seconds are worse, because a wrong duration
    is only visible after a two-minute render.
*/

/**
 * Version is the plan contract's version.
 * It exists so apps/render can refuse a plan it does not understand with a
 * message naming what it supports, rather than drawing three blank scenes.
 * **Additive fields do not bump it**; a change to what an existing field means
 * does. The renderer's rule is the mirror image: ignore fields you do not know,
 * refuse versions you do not know.
 */
export const Version = 1;
export const KindCover = "cover";
export const KindSection = "section";
export const KindStatement = "statement";
export const KindQuote = "quote";
export const KindKPI = "kpi";
export const KindTable = "table";
export const KindChart = "chart";
export const KindClosing = "closing";
/**
 * Scene kinds. These are the values a renderer switches on to pick a component.
 */
export type Kind = typeof KindCover | typeof KindSection | typeof KindStatement | typeof KindQuote | typeof KindKPI | typeof KindTable | typeof KindChart | typeof KindClosing;
export const RevealNone = "none";
export const RevealWipe = "wipe";
export const RevealGrow = "grow";
export const RevealSweep = "sweep";
/**
 * Chart reveal styles. How the mask over the chart image moves — never a
 * redraw, because the pixels underneath are the ones the PDF and the deck
 * already show (locked decision 6).
 */
export type Reveal = typeof RevealNone | typeof RevealWipe | typeof RevealGrow | typeof RevealSweep;
/**
 * Plan is one finished video.
 */
export interface Plan {
  version: number /* int */;
  /**
   * Width, Height and FPS describe the output. They are here rather than in
   * the renderer's config because a plan measured for 1920×1080 is not a plan
   * for any other size: the line breaks in it were decided against that width.
   */
  width: number /* int */;
  height: number /* int */;
  fps: number /* int */;
  /**
   * TotalFrames is the sum of the scenes' frames, carried so the renderer
   * never re-derives the composition's length from a list it might filter.
   */
  total_frames: number /* int */;
  /**
   * Locale is "id" or "en". The renderer uses it for the document language
   * and for nothing else — every word it would otherwise affect is already
   * resolved.
   */
  locale: string;
  /**
   * Title is the document's title, for the player's page title and the
   * video's metadata.
   */
  title: string;
  metrics: Metrics;
  brand: Brand;
  scenes: Scene[];
}
/**
 * Metrics is the surface, in CSS pixels, exactly as it was measured.
 * The renderer positions against these rather than against a stylesheet of its
 * own. That is the point: the numbers a line was wrapped against and the
 * numbers it is drawn against are the same numbers.
 */
export interface Metrics {
  margin_x: number /* int */;
  margin_top: number /* int */;
  margin_bottom: number /* int */;
  content_width: number /* int */;
  body_top: number /* int */;
  body_height: number /* int */;
  title_band: number /* int */;
  footer_band: number /* int */;
  footer_top: number /* int */;
  title_rule_width: number /* int */;
  title_rule_thickness: number /* int */;
  /**
   * Radius is the corner radius on a card, in pixels.
   */
  radius: number /* int */;
  /**
   * Spacing is the vertical rhythm, in pixels. Named rather than numbered so
   * a component asks for a gap by role.
   */
  spacing_sm: number /* int */;
  spacing_md: number /* int */;
  spacing_lg: number /* int */;
  /**
   * Leading is the multiple of the font size one line occupies. It is a
   * float because it is a ratio, and it is the only float here.
   */
  leading: number /* float64 */;
  type: TypeScale;
}
/**
 * TypeScale is the type scale in whole pixels — the print scale at surface
 * scale at 2 px per point, so every size lands on a whole pixel by
 * construction.
 */
export interface TypeScale {
  display: number /* int */;
  h1: number /* int */;
  h2: number /* int */;
  body: number /* int */;
  caption: number /* int */;
}
/**
 * Brand is the tenant's identity, flattened.
 * Colours are `#RRGGBB` and the logo is a data URI, because the renderer has no
 * network (locked decision 4) and no theme package. Nothing here is nullable:
 * an unset accent is the token's own value, resolved before it got here.
 */
export interface Brand {
  name: string;
  /**
   * Primary is the accent on light surfaces; PrimaryOnDark is the same hue
   * lifted far enough to stay legible on the near-black cover, divider and
   * closing scenes. Two fields rather than one because the deck learned this
   * the hard way: a navy that is perfect on paper is invisible on #0A0A0A,
   * and rejecting the navy would be fixing the wrong end.
   */
  primary: string;
  primary_on_dark: string;
  foreground: string;
  background: string;
  muted: string;
  border: string;
  dark: string;
  on_dark: string;
  /**
   * Surface and SurfaceSubtle are the card and the table's header band.
   */
  surface: string;
  surface_subtle: string;
  /**
   * Positive and Destructive colour a KPI delta and a callout. They are here
   * rather than in the renderer's stylesheet for the same reason everything
   * else is: **the renderer holds no palette at all.** A colour literal in
   * packages/motion is therefore always a defect, which is a rule a grep can
   * enforce — where "does this hex match the token?" is a rule only a human
   * can.
   */
  positive: string;
  destructive: string;
  /**
   * Tones are the callout fills, keyed by spec.Tone* — info, warn, good.
   */
  tones: { [key: string]: Tone};
  /**
   * LogoDataURI is empty when the tenant has no usable mark. LogoAspect is
   * its width ÷ height, so the renderer places it by height without decoding
   * the image.
   */
  logo_data_uri?: string;
  logo_aspect?: number /* float64 */;
  /**
   * Credit is the "Made with Argentum" line, or empty when the tenant has
   * switched it off. Confidentiality and FooterNote are theirs.
   */
  credit?: string;
  confidentiality?: string;
  footer_note?: string;
}
/**
 * Tone is one callout's colours: the rule down its edge and the ground behind
 * it. Two fields because a tone that is only a fill is invisible on a coloured
 * ground and a tone that is only a rule is a hairline nobody notices.
 */
export interface Tone {
  accent: string;
  fill: string;
}
/**
 * Scene is one beat of the video.
 * Every payload field for every kind lives on this one struct rather than in a
 * union, for the same reason spec.Section does: the shapes are small, the
 * dispatch is one switch, and a renderer that reads a field another kind wrote
 * draws nothing rather than failing.
 */
export interface Scene {
  kind: string;
  /**
   * Frames is how long this scene is on screen. Always ≥ 1.
   */
  frames: number /* int */;
  /**
   * Title and Subtitle are pre-wrapped: each element is one drawn line.
   */
  title?: string[];
  subtitle?: string[];
  /**
   * Period is the cover's date range, already formatted.
   */
  period?: string;
  /**
   * Lines is the scene's body copy, pre-wrapped. A statement scene carries
   * the lead of one paragraph; a quote scene carries the callout's text.
   */
  lines?: string[];
  /**
   * Facts are the cover's and closing scene's label/value pairs, and a
   * key_value block's rows.
   */
  facts?: Fact[];
  kpis?: KPI[];
  table?: Table;
  chart?: Chart;
  /**
   * Tone is a quote scene's callout tone: info, warn or good.
   */
  tone?: string;
  /**
   * Caption sits under a table or a chart, pre-wrapped.
   */
  caption?: string[];
  /**
   * Notes is the prose this scene is the headline of, whole and unwrapped.
   * The video never draws it — T-V4's player shows it beside the frame, which
   * is where the deck's speaker notes went and the same content.
   */
  notes?: string;
  /**
   * Continued marks a scene carrying the overflow of the one before it. The
   * renderer draws the marker; this says whether to.
   */
  continued?: boolean;
}
/**
 * Fact is a label and a value, both final.
 */
export interface Fact {
  label: string;
  value: string[];
}
/**
 * KPI is one card.
 */
export interface KPI {
  label: string;
  /**
   * Value is formatted — currency symbol, separators, decimals, all decided.
   */
  value: string;
  /**
   * Delta is the period-over-period change as a signed percentage string, or
   * empty. Rising says which way the arrow points and Good says what colour
   * it is: churn going up is not good news, and a renderer that colours every
   * rise green is telling the reader something false.
   */
  delta?: string;
  rising?: boolean;
  good?: boolean;
}
/**
 * Table is a table resolved to strings and pixel widths.
 */
export interface Table {
  header: string[];
  aligns: string[];
  widths: number /* int */[];
  rows: string[][];
  total?: string[];
  /**
   * FontSize, RowHeight and HeaderHeight are pixels. The renderer draws the
   * grid these describe; it does not measure a cell.
   */
  font_size: number /* int */;
  row_height: number /* int */;
  header_height: number /* int */;
}
/**
 * Chart is a rendered chart image and the box it occupies.
 */
export interface Chart {
  /**
   * DataURI is the PNG internal/report/chart drew — the same image the PDF
   * embeds for the same spec.
   */
  data_uri: string;
  width: number /* int */;
  height: number /* int */;
  /**
   * Reveal is how the mask over the image moves. See the Reveal* constants.
   */
  reveal: string;
}
