// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Inbound WhatsApp / Twilio webhook envelopes, from apps/backend/pkg/models.

//////////
// source: models.go
/*
Package models holds shared transport-level message types used by the
WhatsApp providers and webhook handlers. Domain-level entities live in
internal/domain.
*/

/**
 * Message is an inbound WhatsApp / Twilio message normalized across providers.
 */
export interface Message {
  id: string;
  business_id?: string;
  phone_number: string;
  body: string;
  timestamp: string;
  message_type: string;
}
/**
 * AgentResponse is the legacy reply shape used by whatsapp.Provider.SendResponse.
 * New callers should prefer publishing a domain.Message via the chat pipeline
 * and let the WA sink format outbound text.
 */
export interface AgentResponse {
  message_id: string;
  query: string;
  insight: string;
  dashboard_url?: string;
  follow_up_questions?: string[];
  error?: string;
}
/**
 * WhatsAppWebhookPayload models the WhatsApp Business API webhook envelope.
 */
export interface WhatsAppWebhookPayload {
  object: string;
  entry: {
    id: string;
    changes: {
      value: {
        messaging_product: string;
        metadata: {
          display_phone_number: string;
          phone_number_id: string;
        };
        contacts: {
          profile: {
            name: string;
          };
          wa_id: string;
        }[];
        messages: {
          from: string;
          id: string;
          timestamp: string;
          type: string;
          text: {
            body: string;
          };
        }[];
      };
      field: string;
    }[];
  }[];
}
/**
 * WhatsAppMessageRequest is the outbound shape posted to the WA Business API.
 */
export interface WhatsAppMessageRequest {
  messaging_product: string;
  recipient_type: string;
  to: string;
  type: string;
  text: {
    preview_url: boolean;
    body: string;
  };
}
