-- Saved dashboards generated by the agent through create_dashboard tool.
-- Each row links to the originating thread so deleting a thread cascades
-- its dashboards (and we clean them up in Metabase too).
CREATE TABLE IF NOT EXISTS saved_dashboards (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id            UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    thread_id             UUID NOT NULL REFERENCES conversation_threads(id) ON DELETE CASCADE,
    metabase_dashboard_id INT NOT NULL,
    name                  TEXT NOT NULL,
    public_url            TEXT NOT NULL,
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_saved_dashboards_company ON saved_dashboards(company_id);
CREATE INDEX IF NOT EXISTS idx_saved_dashboards_thread ON saved_dashboards(thread_id);
