-- Documents generated by the agent through the generate_document tool.
-- Generic-purpose: invoices, agreements, T&Cs, research summaries, exports —
-- any artifact the agent produces for the user to download. Files live in
-- object storage (MinIO/S3); this row is the metadata needed to re-issue
-- presigned URLs and tie the artifact back to its thread/message.
-- Cascading delete with the parent thread keeps the index lean.
CREATE TABLE IF NOT EXISTS documents (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id  UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    thread_id   UUID NOT NULL REFERENCES conversation_threads(id) ON DELETE CASCADE,
    message_id  UUID REFERENCES messages(id) ON DELETE SET NULL,
    format      TEXT NOT NULL,
    filename    TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    size_bytes  BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_documents_company ON documents(company_id);
CREATE INDEX IF NOT EXISTS idx_documents_thread ON documents(thread_id, created_at DESC);
