package domain

import (
	"context"
	"time"
)

// DBConnection is a tenant-supplied analytical database connection. The DSN
// is stored encrypted at rest; only the database type is in plaintext so the
// agent can dispatch to the right driver.
type DBConnection struct {
	ID           string `json:"id"`
	CompanyID    string `json:"company_id"`
	DBType       string `json:"db_type"` // matches one of internal/adapters/db.Supported
	DSNEncrypted []byte `json:"-"`
	IsDefault    bool   `json:"is_default"`
	Label        string `json:"label,omitempty"`
	// Description is a short hint about what this database contains, used by
	// the LLM agent when picking which source to query.
	Description string `json:"description"`
	// DescriptionSource records how Description was populated:
	//   ""       — uninitialised, autogen pending
	//   "auto"   — generated by the ConnectionDescriber LLM
	//   "manual" — set by the user; autogen must not overwrite it
	DescriptionSource string `json:"description_source"`
	// MetabaseDatabaseID links this row to /api/database when db_type is
	// postgres; nil until registration succeeds via Metabase REST API.
	MetabaseDatabaseID *int `json:"metabase_database_id,omitempty"`
	// EnableTableEmbedding turns on the embedding-based table picker for
	// this source. When true and embeddings exist, the chat runner injects
	// a top-K relevant-table hint into the user's message so the agent can
	// call get_schema pre-filtered instead of dumping the full catalog.
	EnableTableEmbedding bool `json:"enable_table_embedding"`
	// EmbeddingsIndexedAt records when the table_embeddings rows for this
	// source were last (re)built. Nil means never indexed.
	EmbeddingsIndexedAt *time.Time `json:"embeddings_indexed_at,omitempty"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

// Description sources.
const (
	DescriptionSourceAuto   = "auto"
	DescriptionSourceManual = "manual"
)

// ConnectionRepository is the persistence contract for tenant DB connections.
type ConnectionRepository interface {
	Create(ctx context.Context, c *DBConnection) error
	GetByID(ctx context.Context, id string) (*DBConnection, error)
	GetDefaultForCompany(ctx context.Context, companyID string) (*DBConnection, error)
	ListByCompany(ctx context.Context, companyID string) ([]*DBConnection, error)
	Update(ctx context.Context, c *DBConnection) error
	Delete(ctx context.Context, id string) error
	SetDefault(ctx context.Context, companyID, connectionID string) error
}
